### ISSUE TITLE
Should violated concepts be an error in function objects with a single call operator?

### ISSUE THREAD

**Issue by anders-sjogren** [ericniebler/range-v3#107]
Many function objects in ranges, there is only one call operator (`operator()`). One example is `ranges::front_fn`. Since argument dependent lookup (ADL) is disabled by the use of function objects rather than functions, it seems to me that there will never be any alternative function overloads. 

Thus, it seems that violated concepts of these functions objects would be more expressively reported as errors (using CONCEPT_ASSERT_MSG inside the function body) rather than as an SFINAE related message of the type "no matching function for call to object of type ‘const front_fn’".

As discussed [elsewhere](https://github.com/ericniebler/range-v3/issues/94), SFINAE type errors are harder to find the root cause of and patterns leading to such errors (e.g. the use of `CONCEPT_REQUIRES_`) should be limited to situations where they are needed. But I may well have missed some nuance making this needed even in the present case.

**Comment by pfultz2** [comment]
> Many function objects in ranges, there is only one call operator (operator()). One example is ranges::front_fn. Since argument dependent lookup (ADL) is disabled by the use of function objects rather than functions, it seems to me that there will never be any alternative function overloads. 

There are other reasons to constraint functions other than overloading. We can use SFINAE to detect if the expression is valid, which is not possible when the substitution failures are hard errors. For example, I write a lot functions like this:
```cpp
auto print_first = conditional(
    [](const auto& range) -> decltype(std::cout << front(range), void())
    {
        std::cout << front(range);
    },
    [](const auto&)
    {
        std::cout << "Void";
    }
);
```
> Thus, it seems that violated concepts of these functions objects would be more expressively reported as errors (using CONCEPT_ASSERT_MSG inside the function body)

A message can be appended to the `CONCEPT_REQUIRES_` like `CONCEPT_REQUIRES_(Iterable<Rng>() && "The range is not iterable")`. When the compiler points to the `CONCEPT_REQUIRES_`, the message will be there as well. However, gcc doesn't support this yet. 

> rather than as an SFINAE related message of the type "no matching function for call to object of type ‘const front_fn’".

There is also a note for why the function can't be called, something like "candidate template ignored: disabled by 'enable_if'", which shows the types and the `CONCEPT_REQUIRES_` clause.

> As discussed elsewhere, SFINAE type errors are harder to find the root cause of and patterns leading to such errors (e.g. the use of CONCEPT_REQUIRES_) 

The errors related to `CONCEPT_REQUIRES_` do not lead to the same problems when defining the concepts. The problem is compilers have decided that having no backtrace for SFINAE is better(which I disagree with, if you do too, you should express your concern at this almost 3 year old bug [here](http://llvm.org/bugs/show_bug.cgi?id=13309)), which is why diagnosing the definition of a concept predicate is difficult. However, with `CONCEPT_REQUIRES_` there isn't another diagnosis needed in the backtrace.

**Comment by ericniebler** [comment]
Paul has it right. There are good reasons for using SFINAE even when no overload set is being pruned.

**Comment by anders-sjogren** [comment]
Ok. Thanks for the explanation.
