### ISSUE TITLE
filtering after transform triggers transformation again

### ISSUE THREAD

**Issue by ferkulat** [ericniebler/range-v3#1090]
Hi,
if you filter after a transformation the transformation will happen for each following filter.
If the transformation is expensive, this can hit your performance.
I would not consider this a bug. But it was a surprise for me.
Because I expected laziness in this case.

Here is an example:
https://wandbox.org/permlink/CQLK9Uj4NRnJIfKa

With kind regards

**Comment by ericniebler** [comment]
The output is what I would expect. You have gotten what you asked for.

I have in the past considered writing a `view::cache1` adaptor that caches the most recent value to avoid having to recompute it. Something like that might be handy.

**Comment by ferkulat** [comment]
Hi Eric,
my point is: 
I (as a user of your library) expected something different than you as the author.
As the user, I was surprised. Since you highlight lazynes of ranges library.
Since you don't consider this a bug, I would like to ask about documenting it.
And all the other tickets, which express the same expectation, could be an indication that the API or its documentation don't communicate clearly what to expect.

**Comment by ericniebler** [comment]
The documentation is lacking in many ways. I'm curious, though, what about your example leads you to the conclusion that range-v3's `filter` is not lazy? If I can understand your expectation, I can perhaps do a better job on the docs.

Maybe I could explain how `filter` works? A `filter` iterator wraps another iterator `cur` (the range it adapts), and a predicate `pred`. Incrementing a filter iterator evaluates `pred(*++cur)` in a loop until it returns `true`. If `cur` is an iterator into a `transform` view the transformation function must be applied (because that is what the `transform` view does). Once `pred(*++cur)` returns `true`, the `filter` iterator stops advancing `cur`.

Later, when the `filter` iterator itself is dereferenced, it evaluates `*cur`, which causes the transformation function (if `cur` is a `transform` iterator) to be evaluated again.

If you `filter`, `transform`, `filter`, and `filter` again, these effects combine to give the behavior you see.

I just added `view::cache1`. If you add `cache1` after the `transform`, this is the output you see:

```
constructing 2
constructing 4
constructing 6
6

constructing 8
constructing 0
```

https://godbolt.org/z/-KelVv

**Comment by ferkulat** [comment]
Hi Eric,

Thank you for your reply.

Adding `view::cache1` does, what I would expect as a user without looking into the implementation and without the need to add this cache. Even when I don't have lazynes in mind.

I think the need for adding `view::cache1` to avoid multiple constructions is a very important fact to know about.

Thank you very  much.
