### ISSUE TITLE
iterator_category not available in some situations

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#1104]
std::iterator_traits<some_it>::iterator_category is broken on some range-v3 iterators (but not the other traits), in particular the following:

```cpp
#include <iostream>
#include <iterator>
#include <vector>

#include <range/v3/view/join.hpp>
#include <range/v3/view/reverse.hpp>
#include <range/v3/view/transform.hpp>

int main()
{
    std::vector<std::vector<int>> vec{{1,2,3}, {4,5,6}};

    auto v = vec | ranges::view::transform([] (auto && a) { return a | ranges::view::transform([] (auto b) { return b;}); })
                 | ranges::view::reverse
                 | ranges::view::join;

    for (auto && a : v)
            std::cout << a << '\n';

    static_assert(ranges::InputRange<decltype(v)>);

    if constexpr (std::is_same_v<std::iterator_traits<ranges::iterator_t<decltype(v)>>::iterator_category,
                                 std::input_iterator_tag>)
    {
        std::cout << "foo\n";
    }
}
```

Note that the static_assert does not fail, i.e. the view models InputRange, but trying to access the iterator category fails.

This is on GCC8 and Clang6 (independent of concepts).

**Comment by ericniebler** [comment]
This is actually be design, although I admit it is surprising. The trouble is that in this particular case, the `join` view has input iterators that are not `equality_comparable`. Such iterators are legit in the C++20 iterator model (they need not be comparable to themselves, only to their sentinels), but not in the C++17 model. Range-v3, by not providing the nested `::iterator_category` typedef, is trying to tell you -- and the "legacy" STL algorithms -- that this type is not a legacy iterator type.

This is the subject of the following c++20 issue: https://github.com/ericniebler/stl2/issues/583. The proposed resolution there would have `std::iterator_traits<It>::iterator_category` be `std::output_iterator_tag` instead of simply being omitted, but the end result is the same.

**Comment by h-2** [comment]
Thanks for replying. I totally agree and I also discussed with @CaseyCarter in Cologne that right now many views in the standard do not correctly *not* have this or downgrade it properly, e.g. view::iota should have `iterator_category` of  `input _iterator_tag` and only `iterator_concept` of `random_access_iterator_tag` because it generates values.

**Comment by h-2** [comment]
view::transform also doesn't take into account what its reference type is (and whether that should limit it to `input_iterator_tag`) and I think I found others, as well. 
I had wanted to go through all of them and file an LWG issue, but didn't yet find the time.
