### ISSUE TITLE
any_view category decreases performance?

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1178]
Hi!

In the following code
```c++
#include "range/v3/view.hpp"
#include <iostream>

template <typename T>
ranges::any_view<std::pair<T, T>> get_unique_pair_combinations( ranges::any_view<T, ranges::category::random_access> elems )
{

  if ( elems.empty() )
  {
    return ranges::view::empty<std::pair<T, T>>;
  }

  const auto& head       = elems.front();
  auto tail              = elems | ranges::view::tail;
  auto tail_combinations = get_unique_pair_combinations<T>( tail );
  auto head_combinations = tail | ranges::view::transform( [head]( const auto& e ) { return std::make_pair( head, e ); } );

  return ranges::view::concat( head_combinations, tail_combinations );
}

// example:
// input    [ 1, 2, 3, 4 ]
// output   [ { 1, 2 }, { 1, 3 }, { 1, 4 }, { 2, 3 }, { 2, 4 }, { 3, 4 } ]

int main()
{
    auto r = ranges::view::indices( 1000 );
    std::cout << ranges::distance( get_unique_pair_combinations<int>( r ) );
}
```

if I change the function return type
from
```ranges::any_view<std::pair<T, T>>```
to
```ranges::any_view<std::pair<T, T>, ranges::category::random_access>```
the performance decreases about 3x times ( from ~5s to ~15s with an input of 1000 elements, release build ).

That was a bit unexpected. I wonder if I'm missing something or there is some issue involved? tested with gcc 8.3, 1.0-beta branch

Btw I wonder if the current implementation can be tuned somehow ( without writing a custom view implementation ) since even 5 seconds seems too long?

Thanks!

**Comment by ericniebler** [comment]
Type-erasing is expensive. In the worst case, copying a type-erased iterator involves an allocation, which is what `any_view`'s iterators have to do when they are not forward-or-stronger. `any_view` uses a different implementation when it is input-not-forward. Because of the looser semantic requirements on input iterators, copying a type-erased input iterator can simply share the underlying implementation, bumping a reference count. That's way faster than doing an allocation. That explains the difference you're seeing.

**Comment by CaseyCarter** [comment]
> In the worst case, copying a type-erased iterator involves an allocation, which is what any_view's iterators have to do when they are not forward-or-stronger.

I think you mean "when they *are* forward-or-stronger". Since multiple forward iterators can be valid for the same view at the same time, we have to store state (the underlying iterator) in the `any_view`'s iterators. Conversely, since there's only one valid (current) iterator for an input-but-not-forward range we can stuff the underlying iterator into the `any_view` object's state. `any_input_view`'s iterators do no reference counting, they contain vanilla raw pointers to the `any_input_view`.

We perform the same "if there's only one valid value stuff it into the view object" optimization for sentinels of `any_view`s of all traversal categories; `any_sentinel` is also just a wrapper around a pointer to the `any_view`.

We could improve the performance of stronger-than-input `any_view`s somewhat by implementing a small object optimization for `any_cursor` so that it doesn't always allocate for every view. I think there's an issue here somewhere to remind me to do so someday. (As always, pull requests are welcome!)
