### ISSUE TITLE
Allow ints() to take two Integrals of different types

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#121]
Allow `ints()` to take two `Integral`s of different types by adding the following member function to `ints_fn`:

```c++
  template <class From, class To,
            class CT = meta::eval<std::common_type<From, To>>,
            CONCEPT_REQUIRES_(Integral<From>() && Integral<To>()
                              && Integral<CT>() && !std::is_same<From, To>{})>
  take_view<iota_view<CT>> operator()(From from, To to) const {
    return (*this).template operator()<CT>(from, to); // maybe move?
  }
```

The user can right now explicitly do `view::ints<std::size_t>(0, size)`, but this option remains available and `ints` is an utility view anyways. This makes it automatically for the user.

**Comment by ericniebler** [comment]
This encourages signed/unsigned mismatch errors. A better solution IMO would be to provide user-defined literals for the different integer types. So, for instance:

```cpp
std::vector<int> v = /*...*/;
auto ints = view::ints(0_z, v.size());
```

**Comment by ericniebler** [comment]
FYI, `meta` already defined the `_z` user-defined literal suffix.

**Comment by cartec** [comment]
For indices, you have to deal with the fact that `ints` and `iota` return closed ranges. So you actually want `view::ints(0_z, v.size() - 1)`. Except that `v.size()` might be `0`, and then instead of the empty range you get its complement and wacky undefined behavior ensues. I just gave up and wrote:
```
template <typename T, CONCEPT_REQUIRES_(ranges::Integral<T>())>
ranges::take_view<ranges::iota_view<T>> indices(T limit) {
  return ranges::view::take(ranges::view::ints(T{0}), limit);
}
```
to generate [0, `limit`). Given how common half-open integral intervals are in C++, it would be nice to have a primitive range for them in range-v3.

**Comment by ericniebler** [comment]
See #122.

**Comment by gnzlbg** [comment]
> This encourages signed/unsigned mismatch errors.

I've come over time to agree on this and think this would be a mistake. Can we close this?

**Comment by ericniebler** [comment]
Closing this. The comment about the need for `view::indices` is interesting and relates to #277.
