### ISSUE TITLE
Compilation error with iterators from filter and remove if

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#123]
I seem to not be able to get an iterator or const iterator from `view::filter`/`view::remove_if`. 

Is this intended? 

```c++
#include <range/v3/all.hpp>

auto even = [](const int i) { return i % 2 == 0; };

int main() {
  // given:
  auto f0_rng = ranges::view::ints(0, 4) | ranges::view::remove_if(even);
  const auto f1_rng = ranges::view::ints(0, 4) | ranges::view::remove_if(even);
  // (note: you can replace `remove_if` with `filter` here, and reproduce the same problem)

  // this works:
  const auto f0_rng_it = ranges::begin(f0_rng);

  // this fails:
  // const auto f0_rng_cit = ranges::cbegin(f0_rng);
  // const auto f1_rng_it = ranges::begin(f1_rng);
  // const auto f1_rng_cit = ranges::cbegin(f1_rng);

  return 0;
}

```

**Comment by ericniebler** [comment]
By design. See #86. Basically, to make `begin` amortized constant-time for the `remove_if` view, `begin` has to mutate an internally-stored iterator. That means it can't be `const`.

**Comment by gnzlbg** [comment]
Why is this iterator stored in the view and not inside begin?

**Comment by ericniebler** [comment]
What?

**Comment by ericniebler** [comment]
How would storing an iterator inside an iterator work, and how would it make `remove_if_view::begin` amortized constant time?

**Comment by ericniebler** [comment]
P.S. You spent less than 2 minutes thinking critically about my answer. Please try harder to answer your own questions.

**Comment by gnzlbg** [comment]
IIUC the `remove_if` view stores a copy of the begin iterator inside itself.

So then: `const auto f0_rng_cit = ranges::cbegin(f0_rng);` fails because `cbegin(Rng const&)` cannot mutate the range, and the other two fail because the range is const. 

Is that right?

**Comment by ericniebler** [comment]
> Is that right?

Yes.

> I had (and maybe still have) a completely wrong understanding and expectations about how `remove_if` works

The first time you call `begin`, the range caches the position of the `begin` iterator, so the next time it doesn't need to recompute it. The implication is that the predicate must model `RegularFunction`. (But all predicates must be `RegularFunction`s.) The upside is that the vast majority of code in the world that assumes that `begin(foo)` is a cheap call can continue assuming that. The downside is what you have just discovered.

**Comment by gnzlbg** [comment]
I always done it the other way around: O(1) `begin` by finding it on construction, which makes construction O(N) unless the range is default constructed (but who constructs a range and doesn't use begin on it?). 

In your solution with amortized O(1) begin, it seems like begin has visible side-effects but it is still thread safe (worst case a couple of threads would all search for begin at the same time but they would all find the same begin). That is, it might be possible to mutate the state of the iterator via a const member function. That would maintain the user expectations with respect to constness and const iterators. Since one should be able (with the proper iterator categories) to mutate the underlying range through filter, const iterators are to be expected (I expected them, and the error I got in a more complex case was very bizarre). 

I'm going to sleep on this.

**Comment by ericniebler** [comment]
> It might be possible to mutate the state of the iterator via a const member function.

If you mean, `begin` should be const but write to a mutable cache, then I strongly disagree. That would require a mutex and locking, and nobody wants that, I wouldn't think.

> Since one should be able [...] to mutate the underlying range through filter, const iterators are to be expected

I don't understand. If you want to mutate the underlying range, you want *mutable* iterators, not const iterators. But const on the range doesn't matter since ranges have reference semantics. The const-ness of the ranges doesn't have any effect on the const-ness of the elements.

What are you trying to do? Let's start there.

**Comment by gnzlbg** [comment]
> That would require a mutex and locking, and nobody wants that, I wouldn't think.

Above I expressed that this might not be necessary, but it is late. Two threads might go looking for `begin`, one finds it, set it, and mutates the underlying value, so that the other thread finds a different `begin`. Since I don't how bad that is it sounds like you are right and a mutex is required, a mutex there is not worth it.  

Still, amortized O(1) `begin` only means that begin is not O(N) if used multiple times, otherwise is still O(N), paying it on the first call to `begin`, or on construction, is not much of a difference. And doing it on construction would satisfy my expectations because...

> I don't understand. If you want to mutate the underlying range, you want mutable iterators, not const iterators.

Yes, I want mutable iterators, but I expect that if I can get mutable iterators I can also get const iterators. The opposite is not true (e.g. `std::set`). It is weird to be able to get mutable iterators only, and that leads to weird compilation errors.

Maybe one can get "ham-ortized" const iterators, O(1) if someone called a mutable `begin` before, and O(N) otherwise (just joking!). I still prefer finding `begin` on construction better, ... 

> What are you trying to do? Let's start there.

This was my original minimal example (that I minimized further):

```c++
#include <range/v3/all.hpp>

auto even = [](const int i) { return i % 2 == 0; };

template <class> struct A {
  static inline auto integers()
   RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT(ranges::view::ints(0, 4));

  inline auto apply_transform() const noexcept {
    return ranges::view::transform([](const int p) -> int { return 2 * p; });
  }

  inline auto transformed_integers() const
   RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT(integers() | apply_transform());

  inline auto apply_filter() const noexcept {
    return ranges::view::filter(even);
    // return ranges::view::remove_if(even);
  }

  inline auto filtered_integers() const {
    return integers()
           | ranges::view::filter([](const int i) { return i % 2 == 0; });
  }

  inline auto filtered_integers2() const
   RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT(integers() | apply_filter());

  inline auto transformed_and_filtered_integers() const
   RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT(transformed_integers()
                                        | apply_filter());
};

int main() {
  const A<int> a{};
  // this works: transformed integers
  const auto t_rng = a.transformed_integers();
  const auto t_rng_it = ranges::begin(t_rng);
  const auto t_rng_cit = ranges::cbegin(t_rng);

  // this doesn't works: filter integers here
  const auto f1_rng = a.integers() | ranges::view::filter(even);
  const auto f1_rng_it = ranges::begin(f1_rng);
  const auto f1_rng_cit = ranges::cbegin(f1_rng);

  // this works: filtered integers
  // const auto f_rng = a.filtered_integers();
  // const auto f_rng_it = ranges::begin(f_rng);
  // const auto f_rng_cit = ranges::cbegin(f_rng);
  // this doesn't work
  // const auto tf_rng = a.transformed_and_filtered_integers();
  // const auto tf_rng_it = ranges::begin(tf_rng);
  // const auto tf_rng_cit = ranges::cbegin(tf_rng);

  return 0;
}
```

**Comment by ericniebler** [comment]
```cpp
const auto f1_rng = a.integers() | ranges::view::filter(even);
```

But why do you want `f1_rng` to be const? Is there some practical reason?

> Still, amortized O(1) begin only means that begin is not O(N) if used multiple times, otherwise is still O(N), 

Yes, that's why it's "amortized" constant time. Many of the range adaptors call `begin` on their underlying range repeatedly to avoid storing an iterator. They can do this because they know that `begin` will be cheap.

> paying it on the first call to begin, or on construction, is not much of a difference.

There is a difference. Ranges do their work lazily. That's the mental model. *No* work should be done when constructing a range.

Consider that ranges are often created in pipelines where they are then copied repeatedly. A range that stores a cached iterator is like a structure that stores an internal pointer (i.e. a pointer to a member of the struct). That member needs to be reset whenever the structure (range) gets copied. That's an O(N) call. So now, you have an O(N) call to construct a range, and more O(N) calls each time the range is copied. All of which is totally unnecessary. The cache should be computed lazily on the first call to `begin`.

> I expect that if I can get mutable iterators I can also get const iterators. 

Then range-v3 must be a terrible disappointment to you. Many very interesting range types cannot have const `begin` members. Consider the stream ranges, that also maintain an internal cache. Also, `view::for_each` has an internal cache and can't have a const `begin` member. 

If you want to use ranges, you need to let go of the expectation that a const `begin` member exists. Range views are fleeting data structures. Create them, use them, throw them away. Don't declare them const since many are doing work under the covers with hidden mutable state.

**Comment by ericniebler** [comment]
> Range views are fleeting data structures. Create them, use them, throw them away. Don't declare them const since many are doing work under the covers with hidden mutable state.

Just wanted to re-emphasize this point. A range is not a container -- it is a lazy algorithm. Algorithms sometimes have state. State needs to be mutable. So many ranges cannot be const.

**Comment by gnzlbg** [comment]
>Consider that ranges are often created in pipelines where they are then copied repeatedly.
> [...]
> A range that stores a cached iterator is like a structure that stores an internal pointer (i.e. a pointer to a member of the struct). That member needs to be reset whenever the structure (range) gets copied. 

Why does begin have to be recomputed with every copy? If I default construct a range, then begin is not computed. When I assign something to the range (e.g. to make it a view of some data), then begin gets computed. And from now on, it doesn't need to be recomputed any more unless I assign it something else.  The range doesn't hold any data, and it's type doesn't change, so unless the underlying data changes, which doesn't happen when I copy the range, I can just copy the cached begin. No need to recompute anything. (I understand the point of delaying computation as much as possible, I just think that begin might be "too late").

> A range is not a container -- it is a lazy algorithm. Algorithms sometimes have state. State needs to be mutable. So many ranges cannot be const.

I think _this_ is a very useful insight, and a very good way to think about ranges. Thanks. Just for this bit this discussion was very worth it for me. I'll think about this.

 > Then range-v3 must be a terrible disappointment to you. Many very interesting range types cannot have const begin members. Consider the stream ranges, that also maintain an internal cache. Also, view::for_each has an internal cache and can't have a const begin member.

Sadly most of my work involves just indexing structs of arrays, and manipulating these indices as well as the arrays. For I/O I can only use "random-access files", so I haven't need to deal with input ranges and streams yet.

**Comment by ericniebler** [comment]
> Why does begin have to be recomputed with every copy?

Consider:

```cpp
auto rng = istream<string>(std::cin)
    | view::remove_if([](string){...})
    | view::something
    | view::another_thing;
```

The istream view's iterators hold pointers back to the range (since that's where the cached string lives). The `remove_if` view holds a copy of the istream view, and its iterators wrap the istream view's iterators. The `remove_if` range holds a cached begin iterator. With me so far?

Now, if the cached begin iterator is computed (O(N)) in the constructor of `remove_if`, then imagine what happens when the `remove_if` view gets copied -- as it does by the rest of the pipeline. The cached iterator -- which, since it contains an istream view iterator, *also* contains a pointer to the istream view contained in the `remove_if` view -- becomes invalid, since the pointer will be pointing to the wrong istream view. In fact, the istream view it will be pointing at is a member of a temporary that will die at the semicolon, leaving the pointer dangling.

So rather than leaving an invalid iterator in the cache, the `remove_if` view's copy constructor must refresh the cache. At *best* that's another O(N) call. But in this case, we're wrapping an input range (`istream<string>`), so it's really not obvious (to me) what the right thing to do is.

**Comment by ericniebler** [comment]
>> A range is not a container -- it is a lazy algorithm. Algorithms sometimes have state. State needs to be mutable. So many ranges cannot be const.
>
> I think *this* is a very useful insight, and a very good way to think about ranges. Thanks. Just for this bit this discussion was very worth it for me. I'll think about this.

It's one of those not-obvious obvious things that took me a while to really grok. Since this conversation forced me to find words for it, it's been helpful for me, also.

**Comment by pfultz2** [comment]
> A range is not a container

However, containers are ranges which makes the terminology confusing.

> It's one of those not-obvious obvious things that took me a while to really grok. Since this conversation forced me to find words for it, it's been helpful for me, also.

It seems like to me you are doing haskell-like thunks for lazy evaluation. Instead of worrying about thread-safety, you decided to make it always mutable. It makes sense. I just wonder if there is a better way. Perhaps, evaluation could be made explicit. So for lazy views, you don't have a range until its "evaluated" then:

```cpp
const auto f1_rng = view::ints(0, 4) | view::remove_if(even) | eval;
```

Or perhaps `eval` could be used when there is a need for const correctness, otherwise thunks will be used for mutable ranges. Just some thoughts.

**Comment by ericniebler** [comment]
>> A range is not a container
>
> However, containers are ranges which makes the terminology confusing.

In the terminology I'm using, a container is *not* a range, and a range is not a container. They are both iterables.

> ```const auto f1_rng = view::ints(0, 4) | view::remove_if(even) | eval;```

It's more typing, and if you accidentally leave it off you won't get what you're expecting. I prefer to keep it simple.

**Comment by pfultz2** [comment]
> In the terminology I'm using, a container is not a range, and a range is not a container. They are both iterables.

This makes it confusing, changing terminology. I can take a container and use it in a range-based `for` loop:
```cpp
std::vector<int> v = { 1, 2, 3, 4, 5 };
for(auto&& x:v) std::cout << x << std::endl;
```
Same applies to Boost.Range. I can use a vector with a range-based algorithm:
```cpp
std::vector<int> v = { 1, 2, 3, 4, 5 };
boost::ranges::sort(v);
```
 
Because the container is at least a `ForwardRange`. 

However, in ranges-v3 a container is not a range even though it can be used in a range-based for loop, and is a `ForwardRange` in Boost.Range. This is quite confusing.

> you won't get what you're expecting

Which is the current behavior now of the ranges-v3 library.

**Comment by gnzlbg** [comment]
>```c++
auto rng = istream<string>(std::cin)
    | view::remove_if([](string){...})
    | view::something
    | view::another_thing;
```

Good example, this really shows why you are doing it the way you are doing it. Input ranges are really challenging to get right.

>  I can take a container and use it in a range-based for loop:

@pfultz2 Maybe it should be called (in the context of `range-v3`) _iterable-based for statement_ instead.

**Comment by gnzlbg** [comment]
Giving this more thought, functions that take ranges should take them by value, non-const lvalue reference, or rvalue reference, but not by forwarding reference or const lvalue reference.

**Comment by ericniebler** [comment]
By rvalue reference but not by forwarding reference? What's the difference in this case. IMO once this change is implemented (assuming it works the way I think it will), forwarding reference is exactly how ranges should be taken.

**Comment by gnzlbg** [comment]
You are right, a forwarding reference will only be a const& if the range is const. For mutable ranges this will be caught by concept checking on the call site of the algorithm.
