### ISSUE TITLE
unexpected call sequence generated when combining view::filter with other views

### ISSUE THREAD

**Issue by Daniel-G-W-Hug** [ericniebler/range-v3#1254]
I am not sure whether the following is a bug. At least it is unexpected behaviour and quite confusing. Applying view::filter generates an unexpected number of function calls depending on how it is combined with other views. The example uses view::transform with an identity op and filters that always return true to demonstrate the effect.

Code: [main.txt](https://github.com/ericniebler/range-v3/files/3492481/main.txt)
Output: [output.txt](https://github.com/ericniebler/range-v3/files/3492504/output.txt)

Is this a bug?

**Comment by FloopCZ** [comment]
Maybe related to #1220 .

**Comment by dokai** [comment]
I was just about to report a similar issue having observed unexpected calls when using filter. 
```cpp
#include <range/v3/all.hpp>
#include <iostream>
#include <vector>

auto isEven = [](int n) {
  std::cerr << "-> isEven(" << n << ")" << std::endl;
  return n % 2 == 0;
};
auto doubleUp = [](int n) {
  std::cerr << "-> doubleUp(" << n << ")" << std::endl;
  return n * 2;
};


int main() {    
  std::vector<int> numbers = {1, 2, 3, 4};

  auto rng1 = numbers | ranges::views::transform(doubleUp);

  std::cerr << "transform + materialize (vector)" << std::endl;
  auto mat1 = rng1 | ranges::to<std::vector>;

  std::cerr << std::endl << "transform + filter + materialize (vector)" << std::endl;
  auto mat2 = rng1 | ranges::views::filter(isEven) | ranges::to<std::vector>;

  std::cerr << std::endl << "transform + filter + loop" << std::endl;
  for (const auto _ : rng1 | ranges::views::filter(isEven)) {}

}
```
Produces the following output
```
transform + materialize (vector)
-> doubleUp(1)
-> doubleUp(2)
-> doubleUp(3)
-> doubleUp(4)

transform + filter + materialize (vector)
-> doubleUp(1)
-> isEven(2)
-> doubleUp(2)
-> isEven(4)
-> doubleUp(3)
-> isEven(6)
-> doubleUp(4)
-> isEven(8)
-> doubleUp(1)
-> doubleUp(2)
-> isEven(4)
-> doubleUp(2)
-> doubleUp(3)
-> isEven(6)
-> doubleUp(3)
-> doubleUp(4)
-> isEven(8)
-> doubleUp(4)

transform + filter + loop
-> doubleUp(1)
-> isEven(2)
-> doubleUp(1)
-> doubleUp(2)
-> isEven(4)
-> doubleUp(2)
-> doubleUp(3)
-> isEven(6)
-> doubleUp(3)
-> doubleUp(4)
-> isEven(8)
-> doubleUp(4)
```
where we can observe those extra calls when a  `filter` is introduced. Curiously the extra calls differ between materializing to a vector as opposed to consuming it in a loop. The loop seems to have a more consistent pattern (of calling the transform twice) whereas the vector materialization causes redundant calls to both the transform and filter functions.

Wandbox: https://wandbox.org/permlink/83qY2k1sjXxf3QZr

**Comment by ericniebler** [comment]
Case 1:
-------

```c++
  std::cout << "Sequence: v | filter | transform:\n";
  auto rng1 = v | view::filter( [] (int i) {std::cout << "filter: " << i << "\n"; return true;})
                | view::transform( [] (int i) {std::cout << "transform: " << i << "\n"; return i;});
  //std::cout << rng1 << "\n\n";
  std::cout << "[ ";
  for (auto const & e : rng1) {
    std::cout << e << ", ";
  }
  std::cout << "]\n\n";
```

```
Sequence: v | filter | transform:
[ filter: 0
transform: 0
0, filter: 1
transform: 1
1, filter: 2
transform: 2
2, ]
```

This is correct and unsurprising.

Case 2:
--------

```c++
  std::cout << "Sequence: v | transform | filter:\n";
  // not functionally equivalent when not no-op/identity, but still useful for checking sequence of generated calls
  auto rng2 = v | view::transform( [] (int i) {std::cout << "transform: " << i << "\n"; return i;})
                | view::filter( [] (int i) {std::cout << "filter: " << i << "\n"; return true;});
  //std::cout << rng2 << "\n\n";
  std::cout << "[ ";
  for (auto const & e : rng2) {
    std::cout << e << ", ";
  }
  std::cout << "]\n\n";
```

```
Sequence: v | transform | filter:
[ transform: 0
filter: 0
transform: 0
0, transform: 1
filter: 1
transform: 1
1, transform: 2
filter: 2
transform: 2
2, ]
```

This is correct. For each element there are two invocations of the transformation function: once when evaluating the filter predicate, and once when dereferencing the iterator.

Case 3:
-------

```c++
  std::cout << "Sequence: v | transform | transform:\n";
  auto rng3 = v | view::transform( [] (int i) {std::cout << "transform: " << i << "\n"; return i;})
                | view::transform( [] (int i) {std::cout << "transform: " << i << "\n"; return i;})
                | to<std::vector>;
  std::cout << "[ ";
  for (auto const & e : rng3) {
    std::cout << e << ", ";
  }
  std::cout << "]\n\n";
```

```
Sequence: v | transform | transform:
transform: 0
transform: 0
transform: 1
transform: 1
transform: 2
transform: 2
[ 0, 1, 2, ]
```

This one took me a minute, but it's correct. `v | transform | transform` has random access iterators if `v` does also (which, in this case, it does). The `vector` constructor subtracts begin from end to compute the resulting size, preallocates that space, then traverses the range once to initialize all the elements. The traversal makes a single call to both transformation functions.

Case 4:
-------

```c++
  std::cout << "Sequence: v | filter | filter:\n";
  auto rng4 = v | view::filter( [] (int i) {std::cout << "filter: " << i << "\n"; return true;})
                | view::filter( [] (int i) {std::cout << "filter: " << i << "\n"; return true;})
                | to<std::vector>;
  std::cout << "[ ";
  for (auto const & e : rng4) {
    std::cout << e << ", ";
  }
  std::cout << "]\n\n";
```

```
Sequence: v | filter | filter:
filter: 0
filter: 0
filter: 1
filter: 1
filter: 2
filter: 2
filter: 1
filter: 1
filter: 2
filter: 2
[ 0, 1, 2, ]
```

Also correct. Now we're passing forward iterators to the `vector` constructor. The vector traverses the range once to compute the size, does a single allocation, then traverses it a second time to initialize the members.

The second time through, we skip the first element because the filter view caches the first position for which the predicate is true. That gives the filter view amortized constant time `begin()`, which is required by the range concept.

Case 5:
-------

```c++
  std::cout << "Unexpected call sequence. Output mixed in between filter and transform calls (lazy + impl. of operator<< ?):\n";
  auto rng10 = v | view::filter( [] (int i) {std::cout << "filter: " << i << "\n"; /*return i % 2 == 0;*/ return true;})
                 | view::transform( [] (int i) {std::cout << "transform: " << i << "\n"; /* return i * 2;*/ return i;});
  std::cout << rng10 << "\n\n";
```

```
Unexpected call sequence. Output mixed in between filter and transform calls (lazy + impl. of operator<< ?):
[filter: 0
transform: 0
0filter: 1
,transform: 1
1filter: 2
,transform: 2
2]
```

This is an artifact of how `operator<<` is implemented for ranges. First we call `rng.begin()`, which gives us:

```
filter: 0
```

After checking that `it != end`, we `<< *it`, which gives us:

```
transform: 0
0
```

Then we `++it`, which gives us:

```
filter: 1
```

If `it == end` we break; otherwise, we output a `,` and loop.

Hope that clears it all up.
