### ISSUE TITLE
How to declare Range and Slice?

### ISSUE THREAD

**Issue by Hi-Angel** [ericniebler/range-v3#1261]
This library and examples looks amazing, functions are composable and such, but… I spent already some hours walking through all these blog-posts, examples, and still can't figure out one simple thing: how do I make an analog to these 2 structs with the library:

```c++
struct Range {
    size_t start, past_end;
};

template<class T>
struct Slice {
    T *start, *past_end;
};
```

The closest code I got is this `Range<int> r = view::iota(1, 11);` and it doesn't compile.

A big problem I have with all these examples is that they all use `auto` keyword instead of declaring the type explicitly, so I have no idea what type do I get.

**Comment by ericniebler** [comment]
> A big problem I have with all these examples is that they all use auto keyword instead of declaring the type explicitly, so I have no idea what type do I get.

This is intentional. The library encourages you to use pipelines of adaptors, and the resulting types are pretty complex. There are few (not zero) cases in C++ where you need to state the types explicitly.

There isn't a way to declare a `Range` or a `Slice` type to which you can assign the result of any range or slice that range-v3 will create.

**Comment by Hi-Angel** [comment]
Thank you for reply!
