### ISSUE TITLE
MSVC issue with std::bind functor

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1302]
Hi!

The following code:

```c++
#include "range/v3/all.hpp"
#include <vector>
#include <functional>

int map(int x)
{
  return x;
}

void test()
{
  std::vector<int> v;
  ranges::max( v | ranges::view::transform( std::bind( &map, std::placeholders::_1 ) ) );
}
```

fails to compile with MSVC ( tested using 2019 16.2.4 ) while works fine with gcc or clang. Seems like there is some issue with std::bind functor ( since there is no problem with lambda of plain function pointer )

See: https://godbolt.org/z/6u5Wld

Thanks!

**Comment by cpplearner** [comment]
It seems that the expression in question eventually instantiates `ranges::invoke_result_t<const ranges::indirected<ranges::detail::protect<decltype(std::bind(&map, std::placeholders::_1))>>&,std::vector<int>::iterator>`, which tries to instantiate `ranges::indirected::operator()(copy_tag, It...)` (defined at [indirect.hpp#L46](https://github.com/ericniebler/range-v3/blob/117337c4a70851e432a11818c848f649220608af/include/range/v3/functional/indirect.hpp#L46)), which is invalid because there's no enough argument, and MSVC thinks it's a hard error.

**Comment by ericniebler** [comment]
MSVC has 99 problems with range-v3 right now, but `std::bind` ain't one. In the most recent release, there are no uses of `std::bind` in the whole library.

**Comment by cpplearner** [comment]
Well, here `std::bind` comes from user code (the user passed `std::bind( &map, std::placeholders::_1 )` to `transform`).
