### ISSUE TITLE
some core language concepts without std::boolean broken in 0.9.x

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#1322]
```cpp
#include <concepts/concepts.hpp>

struct S
{};

template <typename T>
void foobar(T &&) {}

template <typename T>
    requires concepts::totally_ordered<T>
void foobar(T &&) {}


int main()
{
    std::pair<S, int> p;
    foobar(p);
}
```
(build with `-fconcepts` and GCC)

Instead of the first overload being chosen there is a hard compile error.

**Comment by h-2** [comment]
(likely related to the new syntax for checking "contextually convertible to bool")

**Comment by CaseyCarter** [comment]
`std::pair`'s comparisons aren't constrained before C++20 - and nobody has implemented the spaceship changes for `std::pair` yet AFAIK - so this isn't going to work well in any case. To my knowledge the `totally_ordered` overload will be chosen for all current standard libraries regardless of the template arguments given to `std::pair`.

The GCC issue appears to be yet another occurrence of the "GCC doesn't realize that expressions in *requires-expression*s are unevaluated operands so it instantiates things it shouldn't" bug. I see (cut down a bit from https://godbolt.org/z/UuwUfF):
```
stl_pair.h: In instantiation of 'constexpr bool std::operator<(const std::pair<_T1, _T2>&, const std::pair<_T1, _T2>&) [with _T1 = S; _T2 = int]':
concepts.hpp:1018:9:   required from here
stl_pair.h:472:24: error: no match for 'operator<' (operand types are 'const S' and 'const S')
  472 |     { return __x.first < __y.first
      |              ~~~~~~~~~~^~~~~~~~~~~
```
which is a failure instantiating the body of the `operator<` overload for `std::pair` that the compiler should not instantiate - instantiating the declaration is sufficient - since it is not ODR-used in the program.

This example does compile correctly - and chooses the `totally_ordered` overload - with MSVC which doesn't have this particular bug.

**Comment by h-2** [comment]
> std::pair's comparisons aren't constrained before C++20 - and nobody has implemented the spaceship changes for std::pair yet AFAIK - so this isn't going to work well in any case. 

I was afraid of that, but it's not the crucial point.

> The GCC issue appears to be yet another occurrence of the "GCC doesn't realize that expressions in requires-expressions are unevaluated operands so it instantiates things it shouldn't" bug.

Yes, but if I specify the concepts in the code it doesn't have this behaviour: https://godbolt.org/z/S29AwY
So it's related to your concepts emulation layer, too, or not? Currently we specify the core language concepts in our library ourselves, that's why we didn't see this error.

**Comment by CaseyCarter** [comment]
> So it's related to your concepts emulation layer, too, or not?

Not exactly. The concepts aren't actually checking `convertible_to<bool>`, they're validating that the result is contextually convertible to `bool` by using it as the first operand of a conditional operator. I'm not certain if the concepts use this alternative formulation because @ericniebler wants to investigate it, or of it's due to a shortcoming in the emulation layer. What I *do* know is that `e ? x : y;` in a requires expression triggers the GCC bug that thinks `e` is ODR-used (https://godbolt.org/z/jTTHla).

**Comment by ericniebler** [comment]
Yes, this was an early experiment that snuck into the 0.9 release. I'll switch to testing implicit/explicit convertibility instead of contextual convertibility.

**Comment by marehr** [comment]
@ericniebler Is there any way, I/we can help you with this issue?

**Comment by marehr** [comment]
@ericniebler I just saw that you are working on a new branch called `new-concepts-again`. Is there any chance that you will tackle this issue in that branch?

**Comment by marehr** [comment]
I found out that this Code example isn't compiling with gcc since a long time ago:

https://github.com/ericniebler/range-v3/blob/75ef4fbb51a8be5e3037f602dfc80f2db1a0988c/include/range/v3/utility/concepts.hpp#L396-L407

is the latest definition that I manages to get working.

Some commits later is the commit where you introduced the `concepts/concepts.hpp` header.

https://github.com/ericniebler/range-v3/blob/d3e3ff4cee9c01bac39d784866a11016cd17eb44/include/concepts/concepts.hpp#L668-L679

----

Since the latest working version was defined via `convertible_to`, it would suffice to change the current definition to: (I'm unsure if this will work with the emulation layer and earlier C++ and Compiler Versions)

```patch
diff --git a/include/concepts/concepts.hpp b/include/concepts/concepts.hpp
index cc7b60a0d..9a17544ee 100644
--- a/include/concepts/concepts.hpp
+++ b/include/concepts/concepts.hpp
@@ -874,10 +874,10 @@ namespace concepts
         CPP_concept_fragment(weakly_equality_comparable_with_frag_,
             requires(detail::as_cref_t<T> t, detail::as_cref_t<U> u) //
             (
-                (t == u) ? 1 : 0,
-                (t != u) ? 1 : 0,
-                (u == t) ? 1 : 0,
-                (u != t) ? 1 : 0
+                static_cast<bool>((t == u)),
+                static_cast<bool>((t != u)),
+                static_cast<bool>((u == t)),
+                static_cast<bool>((u != t))
             ));
         template<typename T, typename U>
         CPP_concept_bool weakly_equality_comparable_with_ =
```

another approach could be to make the definition like gcclib does:

```c++
  namespace __detail
  {
    template<typename _Tp>
      concept __boolean_testable_impl = convertible_to<_Tp, bool>;


    template<typename _Tp>
      concept __boolean_testable
	= __boolean_testable_impl<_Tp>
	  && requires(_Tp&& __t)
	  { { !static_cast<_Tp&&>(__t) } -> __boolean_testable_impl; };
  } // namespace __detail


  // [concept.equalitycomparable], concept equality_comparable

  namespace __detail
  {
    template<typename _Tp, typename _Up>
      concept __weakly_eq_cmp_with
	= requires(__detail::__cref<_Tp> __t, __detail::__cref<_Up> __u) {
	  { __t == __u } -> __boolean_testable;
	  { __t != __u } -> __boolean_testable;
	  { __u == __t } -> __boolean_testable;
	  { __u != __t } -> __boolean_testable;
	};
  } // namespace __detail
```
https://github.com/gcc-mirror/gcc/blob/a2d196e75cef95c2b70734ad02e94f9da0e769fe/libstdc%2B%2B-v3/include/std/concepts#L263-L287
