### ISSUE TITLE
Indirect view std::optional issues

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1330]
Hi!

The following code fails to compile on both clang and gcc:

```
#include "range/v3/view/generate.hpp"
#include "range/v3/view/indirect.hpp"
#include <optional>

int main() {
    ranges::views::generate( [](){ return std::optional<int>{ 1 }; } ) | ranges::views::indirect;
}
```

see https://godbolt.org/z/3qKO1F

The code was fine before f914dd74c5337598b52249193a2dffdddddaf4d2 change

Thanks!

**Comment by ericniebler** [comment]
This is by design, I'm afraid. `std::optional` is not sufficiently pointer-like to satisfy the `indirectly_fooable` concepts. In particular, since it does not represent an indirection, it is not insensitive to top-level const and reference qualification as pointers and iterators must be. 

The changeset you reference is part of a fix for a series of National Body comments against C++20.

**Comment by ericniebler** [comment]
I will also point out that, although the code in question may have _compiled_ before, it was almost certainly undefined behavior. You will be iterating over references to values stored in temporary `optional`s that have already been deleted.

It is actually a _good thing_ that this no longer compiles.
