### ISSUE TITLE
Invalid detection of containers

### ISSUE THREAD

**Issue by mattreecebentley** [ericniebler/range-v3#1377]
Currently this only detects containers if they include a begin() returning a const_iterator. Most hand-rolled containers won't include const_iterators

**Comment by johelegp** [comment]
What component of range-v3 are you talking about? Is it, perhaps, `ranges::to`? Including more information, such as actual compiler errors, helps here.

**Comment by mattreecebentley** [comment]
Whatever components are required to detect containers vs other objects, have this issue. For example, ranges::views::all.
Compiler errors aren't relevant.
The issue is as stated.
https://github.com/mattreecebentley/plf_colony/issues/31

**Comment by johelegp** [comment]
You fixed it alright: https://github.com/mattreecebentley/plf_colony/commit/003ab9d7be0f2df85ea7a00bd0f0f4c676ba4f77#diff-da0352006faba8cf5f927d003ec355caR1207.
References aren't iterators.

**Comment by mattreecebentley** [comment]
The issue is as I have stated.
The begin()/end() functions must be able to return const_iterators, not iterators, in order to be detected as containers.
Changing the return to be no a reference had no affect.
If you look into the boost is_container code you will understand this better, but you're not being helpful right now.

**Comment by johelegp** [comment]
Seems like I looked into the wrong place. Could you point out where you touched `const_iterator`s in your code base that made it work with range-v3?

**Comment by mattreecebentley** [comment]
No worries-
in that same link you posted, look at the following lines:
inline PLF_COLONY_FORCE_INLINE const iterator & begin() const PLF_COLONY_NOEXCEPT
inline PLF_COLONY_FORCE_INLINE const_iterator begin() const PLF_COLONY_NOEXCEPT

It changed from const iterator & to const_iterator, same for end(). This is fine for me, but for most hand-rolled containers, people don't both with additional things like reverse_iterators/const_iterators.

**Comment by johelegp** [comment]
Ah, that's it. It's the same. `begin` and `end` should return the iterator by value. Iterators are assumed to be lightweight, so that's how the interface is required to be. The problem wasn't `const_iterator`, but the `&` following it.

**Comment by ericniebler** [comment]
The name `const_iterator` is a red herring. The range library doesn't look for that. It doesn't care at all what you name your iterators.

@johelegp I don't think the `&` is a problem either. The result of calling `r.begin()` is always decayed before its type is tested for `iterator`-ness.

There is a heuristic that tries to tell views apart from containers. I suspect the bit that's tripping you up is that for a (non-`const`) container `c`, the expressions `*ranges::begin(c)` and `*ranges::begin(std::as_const(c))` have different types. For a `std::vector<int>`, the former would have type `int&` and the latter `int const&`. The presence of "deep const-ness" is a tip-off for container-ness.

This is just a guess on the part of the range library, and it can be wrong. That's why there is a trait for overriding the heuristic: `ranges::enable_view`. Set it to `false` for your type.

For the record, the ISO C++ Committee decided that they didn't like the heuristic and removed it from C++20. Everything is a container unless it inherits from `view_base`. I will be following suit in range-v3 eventually, but it's going to break a lot of code. :-(

**Comment by johelegp** [comment]
Yeah, that's what happens for narrowing my view to the iterator and not the container. I have a lot to learn.

**Comment by mattreecebentley** [comment]
> 
> Ah, that's it. It's the same. `begin` and `end` should return the iterator by value. Iterators are assumed to be lightweight, so that's how the interface is required to be. The problem wasn't `const_iterator`, but the `&` following it.

... No. Like I said.
The & return is an OVERLOAD.
There is another begin/end which returns the straight iterator in a non-const way.
Removing the overload LIKE I SAID, has no effect.
The only thing that fixed it was including a begin/end that returned const_iterator, not iterator, not iterator &, not const iterator &.
Stop assuming you know what you're talking about and LISTEN to what people tell you, when you're in an unfamiliar situation. JESUS.

**Comment by mattreecebentley** [comment]
> 
> 
> The name `const_iterator` is a red herring. The range library doesn't look for that. It doesn't care at all what you name your iterators.
> 
> @johelegp I don't think the `&` is a problem either. The result of calling `r.begin()` is always decayed before its type is tested for `iterator`-ness.
> 
> There is a heuristic that tries to tell views apart from containers. I suspect the bit that's tripping you up is that for a (non-`const`) container `c`, the expressions `*ranges::begin(c)` and `*ranges::begin(std::as_const(c))` have different types. For a `std::vector<int>`, the former would have type `int&` and the latter `int const&`. The presence of "deep const-ness" is a tip-off for container-ness.
> 
> This is just a guess on the part of the range library, and it can be wrong. That's why there is a trait for overriding the heuristic: `ranges::enable_view`. Set it to `false` for your range type if it is a container, `true` if it's a view.
> 
> For the record, the ISO C++ Committee decided that they didn't like the heuristic and removed it from C++20. Everything is a container unless it inherits from `view_base`. I will be following suit in range-v3 eventually, but it's going to break a lot of code. :-(

Okay, I think that makes sense from my perspective on what I was experiencing with colony.
I'm glad the committee is removing that for the reason that containers rarely follow those sorts of rules in non-std:: libraries, but I understand why you put it in there.

So it sounds like you're saying that by returning const iterator instead of const_iterator, it wasn't satisfying ranges' requirement for the dereference of the iterator to be const, would that be correct? Or am I getting it wrong?

**Comment by johelegp** [comment]
Ah, sorry. I missed the lack of `_` between `const` and `iterator`.

**Comment by ericniebler** [comment]
> JESUS.

Please be patient and kind. @johelegp was trying to help.

> So it sounds like you're saying that by returning const iterator instead of const_iterator, it wasn't satisfying ranges' requirement for the dereference of the iterator to be const, would that be correct? Or am I getting it wrong?

Yes. There are two ways to tell the range library that your type is a container and not a view:
1. Change your type such that the heuristic guesses correctly.
2. Specialize `ranges::enable_view< your-type >` so that it is `false`.

If you choose option (1), then you would overload `.begin()` on `const`-ness and return a different iterator type that has an `operator*` that yields references-to-`const` rather than references-to-non-`const`.

It's your choice.

**Comment by ericniebler** [comment]
Sounds to me that this is not actually a range-v3 bug but a misunderstanding. Closing. @mattreecebentley pls reopen if you still think there's a bug here.

**Comment by mattreecebentley** [comment]
> 
> 
> Ah, sorry. I missed the lack of `_` between `const` and `iterator`.

No worries. We all make mistakes. Sorry if I lost my rag, I just felt like I was repeating the same thing and you weren't getting it. It came across as a dominance or possibly passive-aggressive thing, and actually wasn't from your end. My bad.



> 
> 
> Sounds to me that this is not actually a range-v3 bug but a misunderstanding. Closing. @mattreecebentley pls reopen if you still think there's a bug here.

From my perspective it's a bug, as it expects a level of compliancy that isn't afforded by the majority of non-std:: containers, but I accept that it will be fixed in due course by the changes necessitated by the committee. So it's up to you whether or not you close it, for now.
