### ISSUE TITLE
no known conversion from ranges::detail::diffmax_t to std::size_t

### ISSUE THREAD

**Issue by david8dixon** [ericniebler/range-v3#1413]
Is this to be expected? 

ranges::detail::diffmax_t a = 1;
std::size_t b = a;

error: no known conversion from ranges::detail::diffmax_t to std::size_t

I am passing a fairly complex composition of ranges to hpx::reduce where std::size_t is used all over the place.

**Comment by CaseyCarter** [comment]
Yes, this is expected. `diffmax_t` is what the C++20 working draft calls [an integer-class type](http://eel.is/c++draft/iterator.concept.winc#2). Such types must be explicitly convertible to integral types (i.e., with `static_cast`), but not necessarily *implicitly* convertible which your code requires.

**Comment by david8dixon** [comment]
As I pointed out, I have a complex range that I am passing into `hpx::reduce`. The error arises in a call to std::distance where the return type is `iterator_traits<InputIterator>::difference_type`. 

I would like to put together a reproducer for hpx, but it isn't clear to me how to do so. Passing ranges::views::iota(1,10) to hpx::reduce didn't generate the error. Any thoughts? Many thanks!

**Comment by ericniebler** [comment]
`iota(1,10)` is a range of integers and can probably use a `long` as the difference type. When you have an `iota` view of, say, `size_t` or `ptrdiff_t`, then you run out of built-in integer types that have a great enough width to represent the difference of the full range, so it spills over to `diffmax_t`. That type, by design, is not implicitly convertible to `size_t` because that would loose precision.

You can explicitly convert it to a `size_t`, but you get what you ask for. That includes possible truncation or UB.

**Comment by gnaggnoyil** [comment]
@ericniebler I'm sorry I don't quite understand. Given `iota_view` already requires `from_ <= to_`, why would a difference_type/size_type for a `iota((uin64_t)0, (uint64_t)0)` needs to be a signed `diffmax_t` instead of merely `uint64_t` itself? I checked libstdc++'s range implementation and it returns `uint64_t` for the size type of `iota_view<uint64_t, uint64_t>`. Which one is correct here?
