### ISSUE TITLE
cannot cartesian_product(enumerate, enumerate) | transform

### ISSUE THREAD

**Issue by david8dixon** [ericniebler/range-v3#1422]
I am enumerating a vector of vectors and then I take the cartesian product of the enumeration with itself (which works fine), but when I try to transform the result it fails. The following link contains the reproducer:

https://wandbox.org/permlink/AL9HJ8pWbBBntXuN

**Comment by pkubik** [comment]
Doesn't work for simpler views too:
```
  auto ints = ranges::views::ints(0, 5);
  auto cp = ranges::views::cartesian_product(ints, ints);
  auto to_one = [](auto&& tup){return 1;};
  auto adjacent_cells_2 = cp | ranges::views::transform(to_one);
```

**Comment by ericniebler** [comment]
> Doesn't work for simpler views too: ...

Nope, that code works fine.

```c++
  auto enumerated = v1 | ranges::views::enumerate;
  auto cp = ranges::views::cartesian_product(enumerated, enumerated);
```

This is a legit problem. After the above, the range library doesn't think `cp` is an input range. That's because it has the following associated types:

value type: `std::tuple<V, V>`, where `V` is `std::pair<std::size_t, std::vector<int>>`
reference: `ranges::common_tuple<R, R>`, where `R` is `ranges::common_pair<std::size_t, std::vector<int>&>`

The computed common reference of these types is:
common reference: `std::tuple<R, R>`, where `R` is `ranges::common_pair<const std::size_t&, std::vector<int>&>`

The trouble is, an lvalue reference to the value type is not convertible to the common reference. `std::tuple` doesn't provide that conversion. The upshot is that the iterators of the `cartesian_product` view do not satisfy `readable`.

I think the problem here is that the computed common reference of `ranges::common_tuple` yields a `std::tuple` instead of another `ranges::common_tuple`.  I suspect making this change will cause other things to break though. I need to think about this.

**Comment by pkubik** [comment]
Sorry, it failed for me when I used a regular reference to for the tuple:
```
 auto to_one = [](auto& tup){return 1;};
```
I didn't compare the error messages carefully enough. Nevermind.
