### ISSUE TITLE
IntelliSense error

### ISSUE THREAD

**Issue by anticrisis** [ericniebler/range-v3#1507]
Apparently there is some history of IntelliSense errors using this library, but I wanted to report a simple test case with the latest Visual Studio Community 2019 Version 16.6.2 on Windows 10, because I couldn't find an issue tracking it. Is there any way to make IntelliSense work properly with the latest tools?

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.13)

project(test LANGUAGES CXX)
add_executable(test test.cpp)

set_target_properties(test PROPERTIES
  CXX_STANDARD 20
  CXX_STANDARD_REQUIRED YES
  CXX_EXTENSIONS NO)

find_package(range-v3 CONFIG REQUIRED)
target_link_libraries(test PRIVATE range-v3::range-v3)
```

```c++
// test.cpp
#include <range/v3/all.hpp>
#include <iostream>
#include <string>

using namespace ranges;

int main()
{
  const std::string s{ "hello, world" };
  auto rev = views::reverse(s);
  std::string rev_s(rev.begin(), rev.end());

  std::cout << rev_s << std::endl;
}
```

This compiles and runs correctly, but IntelliSense gives the following error on `views::reverse`:

```

no instance of function template "ranges::views::view_closure<ViewFn>::operator()
[with ViewFn=ranges::views::reverse_fn]" matches the argument list
		            
argument types are: (const std::string)
            object type is: const ranges::views::view_closure<ranges::views::reverse_fn>

```

Partial IntelliSense command line options:

```
<13500> [IntelliSense] command line options:
	/DWIN32=
	/D_WINDOWS=
	/W3
	/GR
	/EHsc
	/MDd
	/Zi
	/Ob0
	/Od
	/RTC1
	/permissive-
	-std:c++latest
	/IC:\Users\anticrisis\source\repos\cpp\vcpkg\installed\x64-windows\include
```

(Separately, is there a more succinct way to reverse a string using `ranges`? I'm relatively new to C++ and this library.)

**Comment by CaseyCarter** [comment]
(Full Disclosure: I am a Microsoft employee.)

> This compiles and runs correctly, but IntelliSense gives the following error

Generally speaking, you should report disagreements between IntelliSense and MSVC as bugs to Microsoft at [Developer Community](https://developercommunity.visualstudio.com/content/problem/post.html?space=62). You can most easily do so with the Send Feedback tool in Visual Studio:

![image](https://user-images.githubusercontent.com/456873/84578857-cf615080-ad7d-11ea-81b1-9bd79b4ae570.png)

In this particular case I can tell you that the IntelliSense errors are most likely due to the fact that range-v3 uses C++ Concepts in C++20 mode, and despite that MSVC supports Concepts IntelliSense does not yet do so. That support is in progress, but Microsoft hasn't yet announced an ETA.

>  is there a more succinct way to reverse a string using ranges?

If you have a string `s` and you want a separate string with the same content reversed, I think `auto rev_s = s | views::reverse | to<std::string>;` is as good as it gets.
