### ISSUE TITLE
view::indirect does not work on a range of unique_ptr

### ISSUE THREAD

**Issue by blindley** [ericniebler/range-v3#179]
#include <memory>
    #include <range/v3/all.hpp>
    int main() {
        std::unique_ptr<int> vx[1];
        auto rx = vx | ranges::view::indirect;
    }

This fails with a static assertion:

    static assertion failed: The value type of the range passed to view::indirect must be a model of the Readable concept.

It works fine with raw pointers and `shared_ptr`. I presume this is because `Readable` refines `SemiRegular`, which refines `Copyable`. Not sure if this is intended behavior.

**Comment by CaseyCarter** [comment]
I'll conjecture that Readable refines Semiregular because that's what they did in N3351, and it doesn't really matter in N3351 because they only use Readable/Writable as bases for further refinement into iterator concepts. While I find it perfectly reasonable for the iterator concepts to refine Semiregular, none of Readable/MoveWritable/Writable/IndirectlyMovable/IndirectlySwappable/IndirectlyCopyable seem to need copy, move, default construction, or possibly even destruction. I'll take a look at relaxing them if Eric doesn't get to it first.

**Comment by ericniebler** [comment]
I would like `unique_ptr` to model `Readable`. I am fine with moving the `Semiregular` constraint to `WeakIterator`. But removing *all* object constraints from `Readable` makes it a largely meaningless concept. My preference is to make readable types `Movable` or `MoveSemiregular` (as suggested by N3351). @asutton, @sean-parent ?

This would also help in `WeakInputIterator`, where `i++` is merely required to return a type that is `Readable`. Input iterators have to return proxies from `i++` that cache the previous value so that `auto x = *i++` works. Requiring `Readable` to be `Semiregular` makes it nigh impossible to implement input iterators over move-only types.

**Comment by CaseyCarter** [comment]
> This would also help in WeakInputIterator, where i++ is merely required to return a type that is Readable.

Good example; that type must at least be Destructible. I can imagine that I might want to delegate work to another function that returns a Readable, so it would need to be MoveConstructible as well. Can you think of a case in which you would want to assign a type that is *only* Readable?

**Comment by ericniebler** [comment]
Not offhand, but I prefer to err on the side of over constrained.
