### ISSUE TITLE
Cannot copy ForwardRange of variant into a container

### ISSUE THREAD

**Issue by samkellett** [ericniebler/range-v3#240]
I'm not sure if this is a bug or if it's a lack of my understanding but I've been stumped for a while now and can't see where I'm going wrong (and can't make sense of the error) so I figured it may be worth mentioning in case it is actually a bug..

Given a variant of two primitives (int and bool in this case), I can transform an arbitrary random access range into a range of these variants and then copy them into a `std::vector` using `to_` and it works, but if I try the same with a forward range I get errors.

```
#include <range/v3/all.hpp>

#include <boost/variant.hpp>

#include <string>
#include <vector>

int main()
{
  using my_variant = boost::variant<int, bool>;
  std::string is("abcd");

  // this works fine:
  is | ranges::view::transform([](auto) -> my_variant { return 1; })
     | ranges::to_<std::vector<my_variant>>();

  // so does this:
  is | ranges::view::transform([](auto) -> int { return 1; })
     | ranges::to_<std::vector<int>>();
  // and this:
  is | ranges::view::group_by([](auto, auto) { return true; })
     | ranges::view::transform([](auto) -> int { return 1; })
     | ranges::to_<std::vector<int>>();

  // but this does not:
  is | ranges::view::group_by([](auto, auto) { return true; })
     | ranges::view::transform([](auto) -> my_variant { return 1; })
     | ranges::to_<std::vector<my_variant>>();
}
```

Running with the clang in xcode 7.1 with the `std=c++1z` flag.

**Comment by CaseyCarter** [comment]
The error in boost would seem to indicate that something is trying to initialize a `variant<int, bool>` from the iterator type of that range.

The actual container conversion code that gets called is different for the forward range cases: since the random access ranges are sized they call special-case conversion code that reserves space in the vector and uses its `assign(iterator, iterator)` member to perform the conversion. For non-sized-ranges, the conversion code is:
```c++
template<typename Rng,
   typename Cont = meta::apply<ContainerMetafunctionClass, range_value_t<Rng>>,
   CONCEPT_REQUIRES_(Range<Rng>() && detail::ConvertibleToContainer<Rng, Cont>())>
Cont impl(Rng && rng, std::false_type) const
{
  using I = range_common_iterator_t<Rng>;
  return Cont{I{begin(rng)}, I{end(rng)}};
}
```
which could be a call of `vector`'s `initializer_list` constructor if `I` is convertible to `my_variant`.
I'm guessing that the convertibility check is resulting in a hard error in `boost::variant` due to improper constraints. If I replace `boost::variant` with the `variant` from cmcstl2 this program compiles well.

Since it's never the intent of the container conversion code to invoke an `initializer_list` constructor, I think the best solution for this issue is for us to use `()`-initialization instead of `{}`-initialization in `impl`.

**Comment by samkellett** [comment]
That's great, thanks for the explanation and quick fix!
