### ISSUE TITLE
`ints` and `iota` are not compatible with similar facilities in other languages.

### ISSUE THREAD

**Issue by NicolBolas** [ericniebler/range-v3#277]
If you call `view::ints`/`view::iota` with a single value, it assumes that this value is the starting point of an unbounded range. This is inconsistent with similar facilities in other languages.

In Python, [`range` will assume a single value is the terminus of a half-open range starting with 0](http://pythoncentral.io/pythons-range-function-explained/). This is done to facilitate looping over integer ranges:

```
for i in range(11)
```

D's [`iota` function works the same way](http://dlang.org/phobos/std_range.html#iota). A single value means a half-open range starting at 0 and ending with the given value.

I think that the Range library versions should follow existing practice. People may find it confusing to write:

```
for(auto i : view::iota(50))
```

And get an unbounded range starting at 50.

I recognize the importance of being able to create an unbounded range. But I think it would be better to do something like this: `view::iota(50, unbounded)`.

**Comment by gnzlbg** [comment]
While `for(auto i : view::iota(50))` is really convenient, right now the views are just lazy versions of the standard algorithms, so they behave the same (anything else would be surprising). This allows composing iota with `view::take_exactly` to create open and closed ranges among other things.

Having said this, `ints` is a new function introduced for convenience, and I wouldn't mind for it to deviate of what `iota` does, that is, for `view::ints(value)` to generate a `[0, value)` range.

**Comment by pfultz2** [comment]
> Having said this, ints is a new function introduced for convenience, and I wouldn't mind for it to deviate of what iota does, that is, for view::ints(value) to generate a [0, value) range.

+1

**Comment by ericniebler** [comment]
See [this comment](https://github.com/ericniebler/range-v3/issues/121#issuecomment-86204145) from #121

**Comment by gnzlbg** [comment]
@ericniebler that comment does not longer applies, since `ints` now returns a half-open range.

**Comment by gnzlbg** [comment]
So I have a PR (#592)  that implements the semantics discussed here for `ints(N)`, the view remains the same otherwise. 

Currently, `view::ints(N)` returns the range `[N, ...)` which is exactly what `iota` does. That is, currently `view::ints(N)` and `view::iota(N)` are equivalent. So we have two ways of naming the same thing. For me, `view::iota(N)` is clear enough, and when I need this behavior, I use that. OTOH, lots of range-v3 test do use internally ints with this semantics, so I guess others prefer to use `ints` for this instead of `iota`. 

Something that I also need often is what @NicolBolas mentioned in the original issue, that is, returning the ranges [0,N) and [0, N]. I end up needing this way more often than `iota` actually, and I have been using `view::ints(0, N)/closed_ints(0,N)` for this extensively (I never write `view::iota(0) | view::take_exactly(N)` for this). 

So for me it actually does make sense to use `view::ints(N)/closed_ints(N)` to produce the `[0, N)` ranges as well. 

Anyhow, this is a backwards incompatible change, so I think that @ericniebler 's idea of deprecating `ints` and moving it to a `view::indices(N)/closed/inclusive_indices(N)` that has this semantics is probably the better way to go if we are going to break backwards compatibility.

Thoughts?

**Comment by CaseyCarter** [comment]
FWIW, I believe that `view::iota` currently has the correct design: both `view::iota(i)` and `view::iota(i, s)` make sense for any `WeaklyIncrementable` `i` and any `s` with which it is `WeaklyEqualityComparable`. That covers integers and iterators, and likely other things of which we haven't yet thought. It generates exactly the series of elements that `std::iota(i, unreachable{}, result)` or `std::iota(i, s, result)` would generate through its output iterator `result`. `view::iota` is right.

That said, I think it's odd that we have `view::ints` which is almost exactly equivalent to `view::iota`, except that it additionally requires its arguments to have the same type that satisfies `Integral`. I never use `view::ints` with parameters, I only use it bare since it also acts like a value-initialized `iota_view<int>`: `view::ints | view::transform([](int i) { return 2 * i + 1; })`.

I'd be happy if `view::ints` became `namespace view { inline constexpr iota_view<int> ints{}; }` and we introduce a new view with the semantics of python's `range`.
