### ISSUE TITLE
Can the projection function's results be cached?

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#286]
Quick thought: it looks like `max_element()` currently calls the projection function 2(n-1) times but I'm guessing it only strictly needs to call it n times, one for each element. For large n and an expensive (opaque) projection function, the difference could be substantial.

It seem unreasonable for users to hope that, say, `sort()` would cache all its projection results but maybe it's more reasonable to hope that algorithms like `max_element()`, which only need keep track of one projection result at a time, might.

Is it possible to store the result of the projected value for the best result so far without imposing additional requirements on the return type of the projection?

**Comment by ericniebler** [comment]
There are non-obvious implementation difficulties. Consider the current implementation:

```c++
V result = *begin;
while(++begin != end)
{
    auto && tmp = *begin;
    if(pred(proj(result), proj(tmp)))
        result = (decltype(tmp) &&) tmp;
}
```

The result of the projection could be a reference to a move-only type, so you don't want to force a copy. Look what happens when you try to save off the result of the projection:

```c++
V result = *begin;
auto &&proj_result = proj(result); // (1) NEW
while(++begin != end)
{
    auto && tmp = *begin;
    if(pred(proj(result), proj(tmp)))
    {
        result = (decltype(tmp) &&) tmp;
        proj_result = proj(result); // (2) ERROR
    }
}
```

You can't rebind the reference on (2). Instead, `proj_result` needs to be some type that can store a value or a reference, and allows references to be rebound -- something like a `variant`. And once we introduce something like that, I have my doubts that the compiler will be smart enough to optimize it well.

Instead, we assume that  projection functions are simple (since they often are). Keep in mind that in 99% of calls to the algorithm, the projection will be the identity function.

**Comment by tonyelewis** [comment]
Thanks for the response.

Yes, I suspected there might be problems along those lines. Your argument sounds good.

How do you feel about something like a "Recipes" / "Cookbook" section in the docs for commonly encountered issues like these and recommended ways of dealing with them?

For cached projection, I guess there could be something vaguely like the following?

~~~~~.cpp
const auto proj_cache = my_range | view::transform( my_proj )
                                 | ranges::to_vector;
const auto result_itr = ranges::max_element(
   view::zip( my_range, proj_cache),
   my_less,
   [] (const auto &x) { return get<1>( x ); }
);
~~~~~

Though that wouldn't give access to a result iterator into the original range. For this reason and a few others, I've wondered about a view that does the opposite of `view::indirect` (ie has the wrapped range's iterators as its values). Do you think that'd be worthwhile?

Anyway, thanks for your time and I'm happy for you to close this issue.

**Comment by ericniebler** [comment]
> For this reason and a few others, I've wondered about a view that does the opposite of view::indirect (ie has the wrapped range's iterators as its values). Do you think that'd be worthwhile?

You can use `view::iota` for this by passing it a begin and an end iterator.
