### ISSUE TITLE
Should there be a top-level core directory and utility.hpp header?

### ISSUE THREAD

**Issue by rhalbersma** [ericniebler/range-v3#289]
The `range-v3/include` directories `action`, `algorithm`, `numeric`, and `view` have corresponding top-level headers `action.hpp`, `algorithm.hpp`, `numeric.hpp`, and `view.hpp` that include all the headers inside the corresponding directories. 

For `core.hpp`, which includes the other top-level headers, there is no corresponding `core` directory. Should there be one to consolidate the included top-level headers into? 

And there is no catch-all header `utility.hpp` that collects the functionality inside `utility`. Should there be one?

**Comment by CaseyCarter** [comment]
I strongly suspect that Eric's answer to these questions is "no," since otherwise these headers would already exist. If your position is that such headers *should* exist - which I also suspect is the case since otherwise you would have no motivation to post the issue - you should make a supporting argument.

**Comment by rhalbersma** [comment]
My argument is essentially that `core.hpp` seems to be intended as a component header, and therefore I would expect it to collect its included headers from a `core/` directory one level lower in the file hierarchy, similarly to  `algorithm.hpp` and `algorithm/` etc. It will clean up the top-level directory inside `range-v3/include`. But if all the headers currently included by `core.hpp` are meant to be included separately by library users, then that's fine. I just didn't understand the asymmetry with `algorithm` and `view`.

**Comment by gnzlbg** [comment]
Well these are utilities. I some-times need concepts, _or_ variant, _or_ optional, _or_ the tuple algorithms, _or_ some of these together, but I cannot come up with an use case in which someone would want to:

- include _all_ of the current utilities, and
- possible _future_ utilities,

into any given header file. Not even for the `all.hpp` header, since if an utility is not used, why add the weight of an unused utility to the users of the library?

**Comment by ericniebler** [comment]
I don't see a need for a core/ directory or a utility header.
