### ISSUE TITLE
RFC: compressed_pair change

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/range-v3#386]
`compressed_pair` can only compress trivial types. That rules out a large class of empty types that *should* be compressed, most critically `default_sentinel`. I'd like to introduce a pure EBO mechanism "between" the "do nothing" and "use a single static" modes for `compressed_pair`, but doing so will require switching from `.first` notation to `.first()` notation everywhere that `compressed_pair` is used.

Comments?

**Comment by gnzlbg** [comment]
It looks like `compressed_pair` is an implementation detail of range-v3 and not exposed anywhere on its API (from a quick look). If this is truly so I don't mind about the `.first()` notation when using the internal classes / utilities.

Otherwise I still think that it's worth it to pursue this, but maybe it would be worth it to introduce e.g. a `Pair` concept with non-member `first(...)` and `second(...)` and implement (and use) that for all types of pairs (`std::pair`,  `tagged_pair`, `compressed_pair`) and two-element tuples.

**Comment by ericniebler** [comment]
It's fine. The existing `compressed_pair` was a bit of an experiment.
