### ISSUE TITLE
clang-3.9 supports inline variables

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#417]
We should probably start already moving the

```c++
namespace {
  constexpr auto&& foo = static_const<foo_fn>::value;
} 
```

pattern into a macro:

```c++
#define RANGES_V3_INLINE_VARIABLE(type, name) \
  namespace { \
    constexpr auto&& name = static_const<type>::value; \
  } \
  void RANGES_V3_MISSING_SEMICOLON()
```

and switching to 

```c++
#define RANGES_V3_INLINE_VARIABLE(type, name) \
  constexpr type name{}
```

Usage examples: 

```c++
// before
namespace
{
    constexpr auto&& unique = static_const<view<unique_fn>>::value;
}
// after
RANGES_V3_INLINE_VARIABLE(view<unique_fn>, unique);

// before: 
namespace
{
    constexpr auto&& copy_n = static_const<with_braced_init_args<copy_n_fn>>::value;
}
// after
RANGES_V3_INLINE_VARIABLE(with_braced_init_args<copy_n_fn>, copy_n);
```

on clang-trunk: https://github.com/llvm-mirror/clang/commit/3c1c202adacce7479418fdb83d8257e2d9e0f125. Hopefully this would catch any bugs that clang-trunk might have before clang-3.9 is released. The paper is [P0386](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r0.pdf), but I only have access to R0 while the approved one is R2.

What do you think? If you agree with the proposed solution I can submit a PR for this.

I am not sure:

-  of `auto&&` vs `auto const&` for C++<17 (currently range-v3 uses `auto&&` everywhere but the customization point paper used `auto const&` IIRC)

- how to require a semicolon `;` behind the macro that doesn't introduce warnings in C++<17 (a possibility is to add a `void RANGES_V3_MISSING_SEMICOLON()` function declaration behind the macro).

- [cbegin and friends](https://github.com/ericniebler/range-v3/blob/d343d002bfe65264b033c906e83c9eb1c04ba5ef/include/range/v3/begin_end.hpp#L225) are currently constrained on `static_const<begin_fn>::value(rng)` instead of on `begin(rng)`. Some code reordering fixes this, but maybe there was another reason for this that I am missing.

- how to deal with the [`RANGES_GCC_BROKEN_CUSTPOINT` macro](https://github.com/ericniebler/range-v3/blob/3aa5093fe4d4a068318276cef79992ae3465162b/include/range/v3/detail/config.hpp#L285), I read the [bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70552), and truly have no idea what making a namespace inline has to do with that.

**Comment by CaseyCarter** [comment]
I absolutely agree with the general form of the proposal; our weird ODR workaround is right in the wheelhouse of inline variables. I don't have a clang trunk environment handy right now, so I can contribute only encouragement for the time being.

Details:
* I'd like to see this distinction triggered by a new feature `RANGES_CXX_INLINE_VARIABLES` in config.hpp:
```c++
#define RANGES_CXX_INLINE_VARIABLES_11 0
#define RANGES_CXX_INLINE_VARIABLES_14 0
#define RANGES_CXX_INLINE_VARIABLES_17 201606
// ...
#ifndef RANGES_CXX_INLINE_VARIABLES
#ifdef __cpp_inline_variables // We can fix this if SD-6 picks another name
#define RANGES_CXX_INLINE_VARIABLES __cpp_inline_variables
#elif defined(__clang__) && \
    (__clang__major__ > 3 || __clang_major__ == 3 && __clang_minor__ == 9)
// Transition: remove once clang defines __cpp_inline_variables (or equivalent)
#define RANGES_CXX_INLINE_VARIABLES RANGES_CXX_INLINE_VARIABLES_17
#else
#define RANGES_CXX_INLINE_VARIABLES RANGES_CXX_FEATURE(INLINE_VARIABLES)
#endif
#endif
```

* `constexpr auto&` suffices for C++<17. `auto` can absorb the `const`, so `const` is not needed, and the initializers are always lvalues so one `&` is enough.

* No strong preference on how/if we enforce semi-colon after the macro.

* I have a perennially almost-ready-to-submit customization point PR that aligns the CPOs more closely to the latest TS spec that fixes this ordering and what I consider to be minor layering violations (e.g. `cbegin` should use `begin` instead of `begin_fn`). Yes, the ordering is simply for convenience and to avoid repeatedly opening/closing detail namespaces. Do whatever is convenient here and I'll fixup my change, don't hold your breath waiting for me to find time to finish it ;)

* Some versions of GCC have a name lookup bug in which a "hidden" friend discovered during the first phase of name lookup - that sees into inline namespaces - blocks the second phase of lookup that sees into namespaces nominated by `using` directives. A function object named `foo` in a non-`inline` unnamed namespace won't be found if some class declares a hidden friend named `foo`. You should include `RANGES_GCC_BROKEN_CUSTPOINT` in your "C++<17" macro, presumably compilers that support inline variables won't have this particular bug.

**Comment by gnzlbg** [comment]
@CaseyCarter 

> Do whatever is convenient here and I'll fixup my change, don't hold your breath waiting for me to find time to finish it ;)

I have the PR ready but am currently waiting on [this bug](https://llvm.org/bugs/show_bug.cgi?id=28385) getting fixed in order to test it... so if you want to submit that PR first feel free to do so and I'll update mine afterwards.

**Comment by CaseyCarter** [comment]
Looks like we forgot to close this issue after 4cfcb59c3db1c279d72c64ccf15de3c724a0362d.
