### ISSUE TITLE
what is the P proj parameter?

### ISSUE THREAD

**Issue by robertramey** [ericniebler/range-v3#419]
There are a bunch of signatures that look something like this:

`range_safe_iterator_t< Rng > 	operator() (Rng &&rng, C pred=C{}, P proj=P{}) const`

What is the proj parameter? I've poured of the documention and I can't find any explanation

**Comment by gnzlbg** [comment]
It's a projection, you can use it to "project" the elements of the range before passing them to the predicate, for example: 

```c++
sort(range_of_std_pairs, less<>{}, &pairt_t::second);
```

sorts a range of `std::pairs` using less as a binary predicate on the pair's second element.

The docs could certainly use a lot of love.

**Comment by gnzlbg** [comment]
You can read more about projections here [D4128](https://github.com/ericniebler/range-v3/blob/master/doc/std/D4128.md).

**Comment by robertramey** [comment]
I am very interested in this library for a number of reasons.

In particular, I'm interested in your fork of it. - For my purposes I 
see great utility in having constexpr used everywhere that it makes sense.

I see difficulties in getting it beyond it's current state.

a) I understand that eric has a fulltime job AND a new baby (i'm not 
sure about the second)

b) The docs need a huge effort.  Often making good documents has the 
effect of reflecting back to changes in the library itself.

c) making standards language for this library is a separate huge effort.

d) so much so that vendors will likely just incorporate the code from 
this library - which to me conflicts with the whole idea of a "C++ 
standard library" in the first place.

e) looking into the code, I see a number of things which are not obvious 
to me - they look like clever tricks.  Example

auto &&x = *begin, &&y = *mid, &&z = *last;

which looks like it's meant to avoid a copy.  This raises other 
questions like

i) why isn't the argument begin const * & begin

ii) wouldn't this have the side effect of making begin subsequently 
unusable in the function?

f) I'm still thinking about the "project" my first reaction is that it's 
used to transform an function type which would be better done in a more 
explicit and transparent manner.  But I haven't looked at this enough to 
form an argument.

I am actually considering making a professional document for users of 
this library.

Robert Ramey


On 7/3/16 9:41 AM, gnzlbg wrote:
>
> It's a projection, you can use it to "project" the elements of the 
> range before passing them to the predicate, for example:
>
> sort(range_of_std_pairs, less<>{}, &pairt_t::second);
>
> sorts a range of |std::pairs| using less as a binary predicate on the 
> pair's second element.
>
> The docs could certainly use a lot of love.
>
This is a huge understatement
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/ericniebler/range-v3/issues/419#issuecomment-230162443>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AB4R3MCoD3pJOD95N9FPfcPbbZMZs1R9ks5qR-YcgaJpZM4JDx2L>.
>

-- 
Robert Ramey
www.rrsd.com
(805)569-3793

**Comment by gnzlbg** [comment]
>In particular, I'm interested in your fork of it. - For my purposes I
> see great utility in having constexpr used everywhere that it makes sense.

I don't recommend using my fork of it (see below).

> a) I understand that eric has a fulltime job AND a new baby (i'm not
sure about the second)

Eric still does seem to find time to review pull-requests, but it helps a lot if the PR are small and self-contained.  

If someone wants to continue the constexpr approach (e.g. because one needs some algorithms to be constexpr), it would probably be better to send a small self-contained PR for each algorithm that is easy to review (and to reuse the run-time tests for constexpr as much as possible and as long as it makes sense). 

> b) The docs need a huge effort.  Often making good documents has the
effect of reflecting back to changes in the library itself.

The library actually has a lot of docs if you consider that most of the algorithm descriptions can be obtained from the C++ standard, and the Ranges TS. Then there are also a couple of papers that explain the rationale of some parts of the library, and actually pretty good examples and talks that even explain how to create your own views. 

The main issues here is that the Doxygen docs aren't in sync with any of this (maybe I'll try to collect all these links and send a PR some of these days but feel free to give it a try yourself).

Eric has mentioned in multiple occasions that if anybody wants to prepare the library for a submission to Boost (with all the work that does involves) he will support such an endeavor (the library is called range-v3 for a reason I guess). 

But that would be a titanic effort. From the experience with writing some docs for meta, a probably better way to proceed for anybody interested in contributing to pick a small part of the library that raises your interest (e.g. a single algorithm/view/action) and learn how to use it and write some docs for it. A PR for that would receive instant feedback and be greatly appreciated.

> c) making standards language for this library is a separate huge effort.

From an outsider point of view this has actually had more priority. But as you mention above writing this kind of documentation (and having that go through the process) has already resulted in a lot of changes to the library.

> d) so much so that vendors will likely just incorporate the code from
this library - which to me conflicts with the whole idea of a "C++
standard library" in the first place.

I don't know about that. @CaseyCarter can probably comment about the amount of code he has reused from range-v3 in his STL2 implementation, but probably not that much since IIRC one of the points of his implementation was testing that the STL2 can be implemented from the standard wording only. That has also resulted in a lot of improvements to range-v3 itself.

> e) looking into the code, I see a number of things which are not obvious
to me - they look like clever tricks.  Example [...]

I guess the issue here is that at some point these things become obvious and they are used all over the place, so while comments there could help beginners, they would be pretty noisy. It would probably help to collect all these "conventions" in some kind of document about how to write algorithms that can deal well with projections, move iterators, ranges of move only elements, proxy iterators... 

When faced with these questions a good place to look at are the tests of a particular piece of code.

> i) why isn't the argument begin const * & begin

IIRC this is because begin might be returning a move only value (e.g. might be a move iterator over `unique_ptr`s), so if you take it by `auto const&` you cannot move the value again. 

> ii) wouldn't this have the side effect of making begin subsequently
unusable in the function?

`begin` is an iterator, which is not being moved, (the value that iterator points to might be moved out by the dereference), but you can still increment that iterator and go to the next element. You can also move twice out of it, but after the first time you would be moving a value in some valid but unspecified state. 

While range-v3 docs might be lacking, it does actually have a lot of tests (some of them even have comments!), I can't recommend enough for anybody wanting to learn the library to look at the tests.

> I am actually considering making a professional document for users of
this library.

That would be awesome! I would recommend here an "incremental" approach as mentioned above, but any sort of help with the documentation would be greatly appreciated. If you want to go beyond algorithms/view/actions and document other parts of the library (or the utilities e.g. `basic_iterator`...) it would probably make sense to ask here before since some of them are still evolving, and for others some people might already be writing papers.

**Comment by ericniebler** [comment]
Thanks for taking the time to answer these questions, @gnzlbg! Closing this. @robertramey, if you have any other questions, feel free to reopen and post them here.

FWIW, I would *love* for you to work on the docs. I got a volunteer when I recently put out a call on Twitter, but he described himself as "not an experienced C++ programmer." Can I put you in touch with him? Perhaps the two of you can push this forward together.

**Comment by ericniebler** [comment]
Also, to the original question:

@robertramey wrote:
> I'm still thinking about the "project" my first reaction is that it's
> used to transform an function type which would be better done in a more
> explicit and transparent manner.  But I haven't looked at this enough to
> form an argument.

That was my first reaction too, but the idea (which comes from Sean Parent's ASL) makes a lot of sense to me. There are plenty of algorithms like `lower_bound` for which the binary predicate needs to be asymmetric (e.g., binary searching an array of `pair`'s that are ordered by `.second` for a certain integer. The projection makes that symmetric:

```c++
std::pair<int,int> arr[] = {/*...*/};
auto second = &std::pair<int,int>::second;
sort( arr, std::less<>(), second);
auto it = lower_bound( arr, 42, std::less<>(), second );
```

If you try to write the same code without projections, you'll find you need to write two different custom comparison functions: one for `sort` and another for `lower_bound`. That's a pain and introduces maintenance problems.
