### ISSUE TITLE
closed_ints is broken

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#470]
It seems that `closed_ints(first, last)` maps to `iota_view(first, last + 1)` which is obviously broken if `last + 1` overflows, like here:

``` c++
auto rng = view::closed_ints((std::uint64_t)0, std::numeric_limits<std::uint64_t>::max());
// works (weirdly, because of overflow):
  std::uint64_t last0 = *(ranges::end(rng) - 1);
  CHECK(last0 == std::numeric_limits<std::uint64_t>::max());
// fails (remark: unsigned overflow is defined behavior)
  CHECK(ranges::size(rng) != (unsigned long)0); // size == 0 because of overflow
// fails (as a consequence)
  std::uint64_t last1 = 2;
  for (auto i : rng) { last1 = i; }  // because size is zero, nothing happens here
  CHECK(last1 == std::numeric_limits<std::uint64_t>::max());
```

Is there a reason why closed ints maps to `iota_view` instead of closed_iota [here](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/iota.hpp#L494)? Why isn't `closed_iota` actually used? 

Note: `closed_ints((T)0, (T)max)` actually works for most `T`s in 64bit platforms since a _fast_ integer type is chosen (I only got it to fail for 64bit integers in my platform).

**Comment by CaseyCarter** [comment]
The various flavors of `iota_view` are extremely efficient in that their iterators are integers; this representation does not work for ranges with cardinality greater than the largest value representable by the largest signed integral type on a given C++ implementation. When `end - begin` isn't representable by the range's difference type, or `end - begin + 1` isn't representable by the range's size type, you are crossing into infinite range territory.

I would argue that `closed_ints` is not broken, but that it cannot represent the range of all 64-bit unsigned integers by design.

`closed_iota_view` is broken in that most of the cursor methods don't account for the existence of the last  `from_ == to_ && done_ == true` position. I've never bothered to fix it because it's I think it's a bad design: it's better to use a half-open interval over a larger integral type. For "infinite" ranges like [0,2^63), we'd be better off with a range design that doesn't have `size` or iterator difference operations to overflow in the first place.

**Comment by gnzlbg** [comment]
Thanks @CaseyCarter .

Can this happen in any other cases besides: `sizeof(integer_type) == 8`, `is_unsigned<integer_type>`, `first == 0`, and `last == std::numeric_limits<integer_type>::max()`?

We could add some sort of assertion here.

**Comment by ericniebler** [comment]
> For "infinite" ranges like [0,2^64), we'd be better off with a range design that doesn't have `size` or iterator difference operations to overflow in the first place.

I would love to see such a design, FWIW.
