### ISSUE TITLE
No action::reverse?

### ISSUE THREAD

**Issue by adah1972** [ericniebler/range-v3#477]
I have some code that tries to set up a map/dictionary for sorting purposes. My intended usage is:

``` cpp
rmap[join(split(line, '.') | action::reverse, '.')] = line;
```

This is to map the Python code as follows:

``` python
rmap['.'.join(reversed(line.split('.')))] = line
```

Regretfully, the code does not work. I also tried `view::reverse`, but ranges-v3 complains with a static assertion:

> You can't pipe an rvalue container into a view. First, save the container into a named variable, and then pipe it to the view.

Should `action::reverse` be provided? Or any workaround (except following the ranges-v3 prompt, which I know already and regard a bit ugly)?

**Comment by gnzlbg** [comment]
Why can't you do what the `static_assertion` suggests?

While `action::reverse` can be provided (PR welcome), I actually think that for your use case you actually want `view::reverse`. This is a bit hard to tell without seeing the whole code but reversing a range in place to iterate over it afterwards results in 2 iterations over the whole range, while with `view::reverse` you would just need one.

**Comment by adah1972** [comment]
I can and I tried that approach. From the performance point of view, I can see it is better. From the conciseness point of view, I really want to write that code in one line. I was trying to see whether it is possible to make the C++ code as compact as Python...

Let me try another perspective. Do you think it is possible in some way to loosen the requirement as stated in the static assertion? You can see that the range is used and discarded (like the temporary object), so there is no concern (in this specific case) that the view will outlive the object.

**Comment by gnzlbg** [comment]
>  Do you think it is possible in some way to loosen the requirement as stated in the static assertion?

No. For that to work `view::reverse` would need to _own_ the range but views do not own their elements by design. In particular:

> You can see that the range is used and discarded (like the temporary object), so there is no concern (in this specific case) that the view will outlive the object.

The view cannot know this. The solution is simple: use an extra variable as suggested by the static assert. In that way _you_ are in charge of ensuring that the object lives long enough.

It is hard to help you without a minimal contained example, and without knowing where do `split` and `join` come from, but maybe you could write `split` to return a `view` that can be composed with `view::reverse` (instead of a container, or just use [`view::split`](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/split.hpp)), or maybe you really need something like `split(std::move(line), '.') | action::reverse` or similar.

**Comment by adah1972** [comment]
What the code intends to do is very simple. Given a string like "www.yahoo.com", it will do an assignment like:

```cpp
rmap["com.yahoo.www"] = "www.yahoo.com"
```

So I will get a sorted map that naturally put www.yahoo.com and store.yahoo.com together.

**Comment by gnzlbg** [comment]
Right now you can do:
 
 ```c++
auto line_ = action::split(line, '.');
rmap[to_<std::string>(line_ | view::reverse | view::join('.'))] = ...;
```

where the line is `split` eagerly into a vector of `std::strings`, and then this vector of strings is reversed and joined while it is copied into a a temporary string. This allows you to reuse the vector of `std::strings` between iterations as well as reuse the storage of the temporary `std::string` (by using `action::push_back`). 

Sadly you cannot do the whole thing lazily with `line | view::split('.') | view::reverse | view::join('.')` because `view::reverse` requires a `BidirectionalRange` but `view::split` returns a `ForwardRange`.

However, in the future, one could allow the following to work for convenience:

```c++
rmap[line | action::split('.') | action::reverse | action::join('.')] = ...;
```

by:

- [ ] implementing `action::reverse`,
- [ ] improving `action::join` such that it can take a second argument for the intersperse just like `view::join`
- [ ] optionally improving `action::split` to support the pipe operator properly, i.e., `std::move(line) | action::split('.')`. 

Still, while convenient, this last option is going to allocate both a `std::vector<std::string>` and an extra `std::string` at every iteration of your line processing loop... 

The full-lazy option would probably be the best one for your case. I wonder if it is possible to improve `view::split` to make it return a `BidirectionalRange`, @ericniebler ? @CaseyCarter ? Did you tried back then?

**Comment by CaseyCarter** [comment]
> I wonder if it is possible to improve `view::split` to make it return a `BidirectionalRange`

I see no reason that `split` could not model `Bidirectional` when the underlying range (or ranges, when the delimiter is a range as well) also model `Bidirectional`.
