### ISSUE TITLE
Raising the issue of Iterator concepts in the TS

### ISSUE THREAD

**Issue by vinniefalco** [ericniebler/range-v3#479]
I have raised a problem with the Networking TS requirement of **BidirectionalIterator** in some concepts:
https://github.com/cplusplus/networking-ts/issues/42

They suggested I bring it up with the Range TS, so here it is! I am not terribly familiar with the Range TS (although I've used Boost.Range before). Is this the appropriate venue? And is it something that could get attention?

Thanks

**Comment by gnzlbg** [comment]
You probably want to ask in the [STL2 repository](https://github.com/ericniebler/stl2) but IIUC your issue is already solved in both range-v3 and Ranges TS / STL2. 

> And is it something that could get attention?

Check whether the new iterator concepts in the Ranges TS draft solve your issue or not, and if not point to the specific parts of it you have an issue with (you might also want to check the [proxy iterator paper](https://ericniebler.github.io/std/wg21/D0022.html) since it might have some extensions that are not part of the Ranges TS yet).

**Comment by vinniefalco** [comment]
Assuming this document is up to date:
https://ericniebler.github.io/std/wg21/D4128.html#design-decisions-guidelines-and-rationale

Section 3.3.7 "Orthogonality of Traversal and Access Is Not Surfaced in the Iterator Concepts" directly addresses my issue by adopting N3351 as-is. Specifically, this section states:

*"A close reading of the iterator concepts proposed by N3351[21] shows that the problematic requirement on ForwardIterator’s reference type has been dropped. That is, if the concepts proposed by Stroustrup, Sutton, et. al., are adopted, there will be nothing wrong with, say, a random-access iterator with a proxy for a reference type."*

Does this mean that if Ranges TS gets accepted, that it will "modify" all the iterator requirements everywhere else in the standard? Does it mean that the Networking TS will be re-interpreted in terms of these new iterator concept refinements? I'm not particularly good at reading or understanding proposed language.

**Comment by gnzlbg** [comment]
It will probably just mean that the iterators concepts in STL2 will be slightly different than the ones in STL(1). 

> Does this mean that if Ranges TS gets accepted, that it will "modify" all the iterator requirements everywhere else in the standard?

Probably not, since that would break backwards compatibility with a lot of code. It would introduce new concepts. When and how the rest of the library will be updated to use these new concepts remains to be discussed.

> Does it mean that the Networking TS will be re-interpreted in terms of these new iterator concept refinements?

The progress in the Networking TS is mainly orthogonal to the progress in the Ranges TS. The current Networking TS doesn't use Ranges and doesn't depend on the Ranges TS (which is currently not possible since the Ranges TS has not been accepted yet). 

If you really want the new iterator concepts in the current Networking TS the only way to do that would be to make it depend on the un-finished Ranges TS (and wait for ranges before releasing a networking TS). 

Doing that could significantly block progress in Networking, so I doubt something like that would be well received (you could still raise the issue that they might want to design the Networking TS with a port to a future Ranges TS in mind though). Still, not all is lost! A future Networking TS 2 (or 3) can use the Ranges TS without breaking the Networking TS1.

**Comment by vinniefalco** [comment]
Thanks for getting back to me

> It will probably just mean that the iterators concepts in STL2 will be slightly different than the ones in STL(1)

I see, so the Ranges TS proposes that a new namespace is added, with new algorithms and concepts (STL2), and with existing STL unmodified to preserve compatibility?

> If you really want the new iterator concepts in the current Networking TS the only way to do that would be to make it depend on the un-finished Ranges TS

What I'm looking for is much more narrow than that. I think, it doesn't even require Ranges TS, only n3351 (which the Ranges TS adopts as-is). And only a few of the iterator concepts.

Specifically, the Networking TS mandates that buffer sequence iterators meet the requirements of **ForwardIterator** as defined in the current standard. The problem, as explained in D4128, is this particular text from the standard:

**24.2.5 [forward.iterators]**
*6. "If a and b are both dereferenceable, then a == b if and only if *a and *b are bound to the same object"*

This definition precludes making dereferenced iterators return rvalues. Whether it means to or not, a careful reading of n3351 removes this requirement (according to D4128). Thus allowing range adapter iterators returning rvalues to be compatible with the Networking TS.

>If you really want the new iterator concepts in the current Networking TS the only way to do that would be to make it depend on the un-finished Ranges TS (and wait for ranges before releasing a networking TS).

Would it be practical to have just a narrow, focused change in the Networking TS that relaxes the buffer sequence iterator requirements to support rvalues? Maybe there is a way to do this without depending on other proposals? I am not a proposed language expert. And looking over my comments, I realize it might have been more appropriate to also post this as a Networking TS issue.

**Comment by gnzlbg** [comment]
> Would it be practical to have just a narrow, focused change in the Networking TS that relaxes the buffer sequence iterator requirements to support rvalues?

One cannot relax the iterator categories of STL 1 without breaking backwards compatibility. If you were to say that this particular type has the semantics that you want, you would not be even able to call that type a `ForwardIterator` anymore. That's IMO the main issue.

The only realistic way I can see of fixing this is advancing the Ranges TS and then upgrading the Networking TS to use the Ranges TS solution. 

The question that will be asked is: Is it worth delaying the Networking TS 1 just for this change? 

Given that this is not a new problem, that it can be fixed in a future version of the Networking TS, and that in practice standard library implementations have tolerated violations of the ForwardIterator concept to at least try to support proxy iterators... I don't think this is worth it. 

The Networking TS is probably going to need updating anyways once we get Executors and what not, and Ranges might not be that far away.

**Comment by vinniefalco** [comment]
>Is it worth delaying the Networking TS 1 just for this change?

No :)

>Given that...in practice standard library implementations have tolerated violations of the ForwardIterator concept to at least try to support proxy iterators...

Thank you, I suspected this was the case but its nice to hear it from someone with experience. I think this makes "do nothing and keep my fingers crossed" a viable strategy.

I think this is resolved.

**Comment by gnzlbg** [comment]
> I think this makes "do nothing and keep my fingers crossed" a viable strategy.

These issues are important so you should defiantly raise the issue with the Networking TS and probably with your implementation as well.

**Comment by vinniefalco** [comment]
>These issues are important so you should defiantly raise the issue with the Networking TS

I did that: https://github.com/cplusplus/networking-ts/issues/42

>...and probably with your implementation as well.

As far as I can tell, I have two choices:

1. Do nothing, and hope that standard library implementations tolerate variations of the **ForwardIterator** concept.

2. Change Beast adapter iterators to strictly adhere to the **ForwardIterator** requirements.

I'm reluctant to implement option 2 because doing so will add significant complexity and also incur run-time performance penalties. I am thinking to postpone this implementation until a user has an actual problem with the library.

**Comment by CaseyCarter** [comment]
I am concerned that the "relax this particular requirement of this iterator concept" solution leaves users confused. E.g., [path.itr]/2 from N4606 already does what you want:

> A `path::iterator` is a constant iterator satisfying all the requirements of a bidirectional iterator (24.2.6)
except that, for dereferenceable iterators `a` and `b` of type `path::iterator` with `a == b`, there is no requirement that `*a` and `*b` are bound to the same object. Its `value_type` is `path`.

What can I do with this iterator?

1. I can pass it to standard library algorithms that expect an input iterator.
2. I can re-implement forward or bidirectional algorithms myself being sure not to rely on the unsatisfied requirement, and pass the iterator to them.

What percentage of C++ programmers will understand that?

**Comment by vinniefalco** [comment]
> [path.itr]/2 from N4606 already does what you want:

Oh! This is great, thanks for pointing it out!

> A path::iterator is a constant iterator satisfying all the requirements of a bidirectional iterator (24.2.6)
except that, for dereferenceable iterators a and b of type path::iterator with a == b, there is no requirement that *a and *b are bound to the same object. Its value_type is path.

This is acceptable proposed language? I love it! My use-case is completely covered by this.

> What can I do with this iterator?

You left out a 3rd option, implement part or all of compliant standard C++ library.

> What percentage of C++ programmers will understand that?

I'm not an expert, but I think that the standards documents represent contracts written for implementers of compilers and standard libraries. They need specifications in order to know that they are creating a conforming product. I'm not sure that readability for average C++ programmers is a design goal.

**Comment by ericniebler** [comment]
You seem to be missing Casey's point. Concept requirements can't just be casually dropped. The fact that the Filesystem TS does that doesn't make it a good idea or something to emulate. With what algorithms are such iterators guaranteed to work? Only the ones that accept InputIterators. As specified in the standard, these iterators are _not_ ForwardIterators, and they won't be until the Ranges TS lands, or until someone backports the proxy iterators work to STL1.

**Comment by vinniefalco** [comment]
>Concept requirements can't just be casually dropped.

I'm not saying that the buffer sequence iterators **provided** by Networking TS types in the `std` namespace should not meet the requirements of **ForwardIterator**.

I'm saying that **algorithms** provided by Networking TS in the `std` namespace should only require a relaxed version of **ForwardIterator**.

If someone wants their buffer sequence adapter's iterators to work in all STL1 algorithms, they are free to make their iterator types meet the strict requirements of **ForwardIterator**. They will still interoperate with Networking TS.

If someone wants to write a buffer sequence adapter whose iterators return rvalues, and accept that such iterators are not guaranteed to work with all STL1 algorithms, they are free to do so - and can do so confident that their iterators will work with the Networking TS.

My proposed change does not break anything that already exists. Nor does it change the iterators for types provided by the Networking TS. It only changes algorithms in the Networking TS to be more permissive *in the types of iterators they accept*. Or am I confused? How does allowing a new algorithm to accept a less narrow type break anything?

**Comment by ericniebler** [comment]
Ok. That wasn't clear to me.

**Comment by CaseyCarter** [comment]
>  How does allowing a new algorithm to accept a wider type break anything?

It doesn't *break* anything, but it raises the barrier for implementation. If I'm considering implementing the Networking TS then every algorithm I want to use with these iterators must be reimplemented / audited to properly support the relaxed requirements. Since I have no machinery to detect these iterators and discriminate them from other input iterators, realistically I need to implement distinct algorithms or design some advanced tagging machinery to support using them with my existing algorithms.

I can't say for certain that this relaxation will reduce the number of Networking TS implementations we'll see, but it will require more effort on the part of implementors and result in buggier implementations.

**Comment by gnzlbg** [comment]
@CaseyCarter Currently the Networking TS does not use concepts so... whether you want to offer some kind of concept-checking or not as a part of your implementation (or just rely on `iterator_traits` and basic tag dispatching) is a quality of implementation issue. 

When the Networking TS is upgraded to use concepts chances are that the concepts in the Ranges TS will be available as well, and one can then just use the new iterator concepts which solve this problem.

**Comment by vinniefalco** [comment]
@CaseyCarter 

You really have to go out of your way to write an algorithm that depends on the strict aliasing requirements of **ForwardIterator**. Boost.Asio is completely tolerant of relaxed iterators. And so are almost all standard library algorithms. As was stated earlier, _"in practice standard library implementations have tolerated violations of the ForwardIterator concept to at least try to support proxy iterators"_

I don't think its possible to detect if an iterator type meets the strict aliasing requirements.

**Comment by HowardHinnant** [comment]
Data point:  All of the libc++ algorithms in `<algorithm>` are known to work with `vector<bool>::iterator`.  This was a conscious design decision on my part, and the required effort was virtually non-existent except for writing the appropriate tests.

**Comment by vinniefalco** [comment]
The issue of iterator requirements in the Networking TS is now in the Active Issues List:
http://cplusplus.github.io/LWG/lwg-active.html#2779

**Comment by ericniebler** [comment]
I don't see an issue here that effects either range-v3 or the Ranges TS, so I'm closing this.

If you want to loosen the requirements on algorithms on the Networking TS, that is up to the project editor of that TS. I would point out that the proposed wording of LWG#2779 essentially says, "these types are not quite BidirectionalIterators", but it doesn't change the requirements of any algorithms to say, "this algorithm works with types that are not quite BidirectionalIterators", so I don't know what it accomplishes.
