### ISSUE TITLE
Iterator concept wrong?

### ISSUE THREAD

**Issue by rrahn** [ericniebler/range-v3#624]
Hi, 

first of all thanks for this great work!
I stumbled upon something that I need a bit of a clarification for?!
According to the _iterator concept_ specification (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4651.pdf §9.3.8), the _iterator concept_ requires the weakly _incrementable concept_ and that the type ```i``` can be dereferenced.
However in https://github.com/ericniebler/range-v3/blob/master/include/range/v3/utility/iterator_concepts.hpp#L280 the _iterator concept_ also refines the _copyable concept_, such that pure output iterators like the ```std::ostream``` iterator are not being recognized as _output iterators_. 
Am I missing something here?

**EDIT**
Ok, I just looked again deeper into the _weakly incrementable concept_, which refines the _semi regular concept_, which again allows copy construction. 
However,  according to http://en.cppreference.com/w/cpp/concept/OutputIterator, the pure output iterator implementations do not implement the copy constructor?! I mean it makes kind of sense that an ```ostream_iterator``` cannot be copied. Otherwise, one could write into the same destination through multiple single-pass iterators, who might "steal" the ```stream_buffer``` through overflow operations. So is the _iterator concept_ to strong for output iterator implementations?

**Comment by CaseyCarter** [comment]
Both standard and Ranges TS output iterators require copyability through refinement of their respective `Iterator` concepts (http://en.cppreference.com/w/cpp/concept/Iterator, http://en.cppreference.com/w/cpp/concept/Iterator). They *do* differ with respect to default construction: all categories of iterators in the TS design are `Semiregular` and therefore `DefaultConstructible`, whereas standard C++ only requires default constructibility for `Forward` iterators.

The usual recommendation is to avoid the problem by using the range-v3 output iterators instead of the standard library output iterators. In particular, range-v3 does have an implementation of `ostream_iterator`.

**Comment by rrahn** [comment]
Ok, many thanks for the clarification.
