### ISSUE TITLE
Is there iterate_view?

### ISSUE THREAD

**Issue by trha** [ericniebler/range-v3#626]
Given a function f and an initial value x, this view should generate an infinite range of repeated applications of f to x: `{x, f(x), f(f(x)), ...}`.

**Comment by CaseyCarter** [comment]
Range-v3 doesn't have this exact view, but it does have `generate_view` which returns the result of successive invocations of a function. Your `iterator_view` appears to be equivalent to `view::generate([x, f]() mutable { x = f(x); return x; })`.

**Comment by trha** [comment]
Thanks, that seems easy enough to add. I'm just finding the equivalent of Haskell's list functions in range-v3.

**Comment by CaseyCarter** [comment]
Woops, I lied: the first element of `view::generate([x, f]() mutable { x = f(x); return x; })` is `f(x)` instead of `x`. You want `view::generate([x, f]() mutable { auto tmp = x; x = f(x); return std::forward<decltype(tmp)>(tmp); })` or the C++14-ier `view::generate([x, f]() mutable { return std::exchange(x, f(x)); })`
