### ISSUE TITLE
CMakeLists.txt - Error when using add_subdirectory(range-v3) from CMakeLists.txt of parent project

### ISSUE THREAD

**Issue by Marc--Olivier** [ericniebler/range-v3#671]
On `master`, commit 6dba64d0073ffeb8e33e643e1e8e32be70dee935

When range-v3 was in a subdirectory of a project foo and `add_subdirectory(range-v3)` is called from the CMakeLists.txt of project foo, an error message is raised when running cmake:
```
CMake Error at range-v3/cmake/TestHeaders.cmake:93 (message):
The `HEADERS` argument must be provided.
Call Stack (most recent call first):
range-v3/CMakeLists.txt:103 (generate_standalone_header_tests)
```
`RANGE_V3_PUBLIC_HEADERS` is empty, because the variable `CMAKE_SOURCE_DIR` is used.
See [bug-CMakeLists.zip](https://github.com/ericniebler/range-v3/files/1082412/bug-CMakeLists.zip)

Using `CMAKE_CURRENT_SOURCE_DIR` instead fixes the issue (see attached patch file 
[range-v3_FixCMakeLists.txt](https://github.com/ericniebler/range-v3/files/1082413/range-v3_FixCMakeLists.txt)).

**Comment by ericniebler** [comment]
Make a pull request?

**Comment by tahonermann** [comment]
My impression is that cmake is not really designed for projects to be plugged together via add_subdirectory.  For the range-v3 dependent port of text_view, I took the approach of creating a cmake find package module for range-v3; see https://github.com/tahonermann/text_view-range-v3/blob/master/cmake/modules/FindRange-v3.cmake.  Ideally, range-v3 would provide/install a find package module itself via cmake <tt>CMakePackageConfigHelpers</tt> and <tt>configure_package_config_file()</tt>; see https://cmake.org/cmake/help/v3.0/module/CMakePackageConfigHelpers.html.  I've considered proposing and contributing something along these lines, but haven't so far made the time to do so.

**Comment by FloopCZ** [comment]
@tahonermann maybe you can add a new issue that range-v3 should have `RangeV3Config.cmake` and `RangeV3Version.cmake` package helpers. Range-v3 as of right now, however, uses no special compiler flags, has no compiled libraries, and has no optional components, thus it would not benefit that much from this functionality. Although one benefit is (since range-v3 has semantic versioning now) that you could be sure that the version of range-v3 installed in your system is the one mentioned in the `CMakeLists`, so it is probably still worth the few lines of CMake code.
