### ISSUE TITLE
Compilation problem in random.hpp

### ISSUE THREAD

**Issue by mirth** [ericniebler/range-v3#693]
Don't know if it is actual bug but the problem occured after i've updated the library. Xcode 8.3.2, Apple LLVM version 8.1.0 (clang-802.0.42).

```
range/v3/utility/random.hpp:570:24: error: thread-local storage is not supported for the current target
                static __thread bool initialized = false;
                       ^
range/v3/utility/random.hpp:571:24: error: thread-local storage is not supported for the current target
                static __thread meta::_t<std::aligned_storage<
```

**Comment by CaseyCarter** [comment]
random.hpp uses thread-local storage to provide per-thread default random number engines so that multiple threads can e.g. call `sample` or `shuffle` without providing an explicit engine and have reasonable performance.  Xcode didn't support `thread_local` before version 8 -  and apparently still does not support it unconditionally - so there's some fallback code that sometimes uses `__thread` instead:

```c++
#ifndef RANGES_CXX_THREAD_LOCAL
#if defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED <= 70100
#define RANGES_CXX_THREAD_LOCAL 0
#elif defined(__IPHONE_OS_VERSION_MIN_REQUIRED) || \
    (defined(__clang__) && (defined(__CYGWIN__) || defined(__apple_build_version__)))
// BUGBUG avoid unresolved __cxa_thread_atexit
#define RANGES_CXX_THREAD_LOCAL RANGES_CXX_THREAD_LOCAL_PRE_STANDARD
#else
#define RANGES_CXX_THREAD_LOCAL RANGES_CXX_FEATURE(THREAD_LOCAL)
#endif
#endif
```

I don't have access to a Mac to maintain this mess, it's all the result user feedback. Can you provide more information on your environment?  Are you targeting MacOS or IOS etc?

**Comment by CaseyCarter** [comment]
Absent any more detail, I assume this problem has gone away.
