### ISSUE TITLE
group_by does not GroupBy

### ISSUE THREAD

**Issue by FreeApophis** [ericniebler/range-v3#738]
I actually was looking for an efficient way creating a lazy Group By myself and checked out the implementation of range-v3 for ideas.

Simple Example in C#

    var values = new List<int>{0,1,2,3,4,5,6,7,8,9};
    values.GroupBy(i => i % 3, i => i)

Results in 3 Groups {0,3,6,9},{1,4,7},{2,5,8}

The range-v3 equivalent

    std::vector<int> values= {0,1,2,3,4,5,6,7,8,9};
    values | ranges::view::group_by([](int p0, int p1) {return p0 % 3 == p1 % 3; })) {

Results in 10 ranges of length 1: {0},{1},{2},{3},{4},{5},{6},{7},{8},{9}

Obviously I could sort the vector by the order-criterion before using the view. But isn't that the point of group_by?

    std::vector<int> values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
    ranges::sort(values , [](int p0, int p1) {return p0 % 3 < p1 % 3; });
    values | ranges::view::group_by([](int p0, int p1) {return p0 % 3 == p1 % 3; })) {

Of course you could just mean something different when using the term "group by", however this is very misleading since you contradict other implementations in the same area. If it is meant to work like this, I would suggest another name, "partition" would come to mind.

**Comment by gnzlbg** [comment]
If you look at the [requirements](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/group_by.hpp#L144) of `range-v3`'s `view::group_by`, you will see that it works on `ForwardIterators`. 

This means that to obtain the behavior you want it would need to traverse the sequence and store references to the elements (or the elements themselves) in a container.

If you want that behavior you can probably do this yourself beforehand, and then pass the result to `group_by`, or write your own `View` that does this (e.g. contains a collection of references to the elements) and builds on top of `group_by`. The later might be a bit tricky if the range returns rvalues because the collection of references must be turned into a collection of values which would mean that this lazy algorithm can't model `View` (`View` requires `O(1)` copy, which can't be achieved if the `View` stores `O(range::distance(rng))` elements). 

I don't have a lot of experience with garbage collected languages but it might be that C#'s behavior is easy if garbage collection is available. 

---

From the range-v3 docs:

> `view::group_by`:
>
> Given a source range and a binary predicate, return a range of ranges where each range contains **contiguous elements** from the source range such that the following condition holds: for each element in the range apart from the first, when that element and the first element are passed to the binary predicate, the result is true. **In essence, view::group_by groups contiguous elements together with a binary predicate**.

Rust's [`group_by`](https://docs.rs/itertools/0.6.0/itertools/trait.Itertools.html#method.group_by) has a similar definition: 

> Return an iterable that can group iterator elements. Consecutive elements that map to the same key (“runs”), are assigned to the same group.

And so does D's `chunkBy`:

> Chunks an input range into subranges of equivalent **adjacent elements**. In other languages this is often called partitionBy, groupBy or sliceWhen.
>
>Notes:
>
>Equivalent elements separated by an intervening non-equivalent element will appear in separate subranges; this function only considers adjacent equivalence. Elements in the subranges will always appear in the same order they appear in the original range.

They all seem to be motivated by avoiding implicit memory allocations when possible.

**Comment by FreeApophis** [comment]
I had the feeling that this was by design, obviously there are two different semantics which both are named "GroupBy" out there (I would prefer ChunkBy, but I am probably biased because of previous experiences) Haskell agrees in it's semantics of group_by with the C++ version.

I agree that it would be very difficult to have such a view, thats why I was curious how ranges solved it. I could imagine a solution with multiple scans without an additional storage, however the naive complexity would be O(n*m) where m is number of Groups.

LINQ's naming is often a bit odd, because they did not use the functional names, they rather modeled it after SQLs naming:  But for GroupBy C# is not alone, Rubys group_by() and Pythons groupby() have the same semantics.

Since this is mere semantic ambigiuity, you can close the issue. It is solved for me. Thanks.

**Comment by gnzlbg** [comment]
The fastest solution is probably to sort your range in place unless the elements are too big. If you can't do that or your elements are too big just create a vector of pointers to the elements (e.g. a [`boost::ptr_vector<T>`](http://www.boost.org/doc/libs/1_65_1/libs/ptr_container/doc/ptr_vector.html)), sort that instead, and pass it to the `view::group_by` view.  If you are not going to iterate over all your elements you can just sort only the number of elements that you need.

In any case, benchmark.
