### ISSUE TITLE
How to test noexcept in concepts?

### ISSUE THREAD

**Issue by akrzemi1** [ericniebler/range-v3#756]
Maye it is not the intended purpose of the library, but I figured out it could be used for declaring and using custom concepts. I tried to use it to check if a given type `T` has member function `f` which is declared `noexcept`. The only solution I came up with is this:

```c++
struct is_acceptable_r
{    
  template<class T>
  auto requires_(T&& x) -> decltype(concepts::valid_expr(
      concepts::is_true(std::integral_constant<bool, noexcept(x.f())>{})
  ));
};
```
But maybe there is a better way for checking `noexcept` in this library?

(Here is a full example illustrating my intentions: https://wandbox.org/permlink/97jwJdMUUdwyHJRE)

**Comment by CaseyCarter** [comment]
> Maybe it is not the intended purpose of the library, but I figured out it could be used for declaring and using custom concepts

Not the primary purpose, but definitely a secondary purpose. The point of the library is to be a vehicle for ranges development, and ranges in the TS are constrained with concepts. Emulating concepts in this library isn't absolutely required, but it does help to keep things closer to the specification.

`noexcept` constraints don't come up very often, though, so there's no specific support for them. If I were to constrain an expression to be `noexcept` I would use `concepts::is_true` exactly as you've done here. There are in fact *no* `noexcept` constraints in the Ranges TS since we reformulated `Destructible` in terms of the `is_nothrow_destructible` trait rather than using expression constraints a la:

```c++
template<class T>
concept bool Destructible = requires(T& t) {
  { t.~T() } noexcept;
};
```

> I tried to use it to check if a given type `T` has member function `f` which is declared `noexcept`.

What you actually have here is a check that the expression `x.f()` for an lvalue `x` of type `T` is valid and not potentially throwing - which is close, but not exactly "`T` has a member function `f` which is declared `noexcept`". For example, `f` could be a function object:
```c++
struct S1 { void (*f)() noexcept; };
struct S2 { static struct { void operator()() noexcept; } f; };
```
or a reference thereto. Before C++17, `f` could even be potentially-throwing if it is `constexpr` and doesn't perform lvalue-to-rvalue conversion on `*this`:
```c++
struct S3 {
    constexpr int f() const { return 42; }
};
```

I point this out not to be pedantic but to help you get into the C++ Concepts mindset: concepts in C++ are about constraining expressions, not signatures.

**Comment by akrzemi1** [comment]
Thanks for the explanation.
