### ISSUE TITLE
How to count elements in a sequence?

### ISSUE THREAD

**Issue by daixtrose** [ericniebler/range-v3#767]
This code does not compile:

```c++
inline void understand_ranges_v3()
{
    using ranges::view::remove_if;
    using ranges::view::reverse;
    using ranges::view::transform;

    std::vector<double> someNumbers = { 
        0.0, 1.0, 2.0, 3.0, 
        4.0, 5.0, 6.0, 7.0, 8.0 };

    auto outsideOfReasonableRange = [](double d) { return d > 5.0; };
    auto addTwo = [](double d) { return d + 2.0; };

    auto filteredSequence = someNumbers
        | remove_if(outsideOfReasonableRange)
        | transform(addTwo)
        | reverse;

    ranges::size(someNumbers); // compiles
    ranges::size(someNumbers | remove_if(outsideOfReasonableRange)); // Ouch!
    ranges::size(filteredSequence); // Dito Ouch!
}
```

Is there any other elegant way to obtain the number of items within the modified sequences?

**Comment by CaseyCarter** [comment]
> Is there any other elegant way to obtain the number of items within the modified sequences?

`size` is always O(1). Since there's no way to obtain the size of a filtered view in O(1) time, the result `View` of `view::remove_if` does not implement `size`. Similarly, the result of composing a non-sized `View` with other view adaptors is almost certainly not a sized view.

If you want to know how many elements are in a range and you don't mind potentially linear time, you want `ranges::distance(filteredSequence)`.
