### ISSUE TITLE
Workaround to return subrange of transformed range?

### ISSUE THREAD

**Issue by seertaak** [ericniebler/range-v3#779]
Hi, I have code that looks like this:

        // get the region ui's (called RegionNode) from the vector of pointers to polymorphic base.
        // I know that this is ugly but it could be described as legacy code!
        auto regions() const {
            // child_pointers() is a std::vector<zui::node>, zui::node is the base class of RegionNode below.
            // the child_pointers() can be any zui::node, but in this specific case, we know that 
            // children 1,..., child_pointers().size() - 1 are in fact RegionNode; hence the call to rsv::tail.
            return child_pointers() | rsv::tail | rsv::transform(
                       [](auto&& cp) { return std::static_pointer_cast<const RegionNode>(cp); });
        }
        
        // the regions partition time. grab any regions that intersect with the time interval [t, T)
        auto regions_during(double t, double T) const {
            auto rs = regions();
            
            auto b = rs::lower_bound(rs, t, rs::less(), [] (auto&& r) {
                return r->region()->time().end;
            });
            auto e = rs::upper_bound(rs, T, rs::less(), [] (auto&& r) {
                return r->region()->time().begin;
            });
            
            return rs::make_iterator_range(b, e) ;
        }

This code fails, and I think the reason is that when `rng` goes out of scope, the iterators `b` and `e` which are returned "lose the mother ship". Is my intuition correct? If so, what would be the preferred workaround? My guess would be to use `b.base()` and `e.base()`, and then to apply the `rsv::transform` again. It would be nice to not have to repeat the `rsv::transform`. I thought that using `rs::get_unsafe` would work (so `b`, and `e`, would be replaced by `rs::get_unsafe(b)` and `rs::get_unsafe(e)`, respectively, in the final call to `rs::make_iterator_range()`), but this is *not* the case. 

Is there any way of asserting that the "backing" of the iterators remains? The reason I'm a bit surprised this doesn't work is that the alternative way -- namely using old-school `std::{lower,upper}_bound` and re-applying the `rs::transform` at the end *does* work. Basically, the backing vector exists beyond the return point of `regions_during`, so the call makes sense.

[As a meta question, is it preferred that I submit these types of questions to stackoverflow?]

**Comment by ericniebler** [comment]
The "backing" of the iterators, if you mean the `vector` of nodes, remains valid (assuming that `child_pointers()` returns a reference to a `vector`, which it must since the code apparently compiles).

The trouble you're probably running into is that the `transform_view` stores the transformation function. The `transform_view`'s iterators (`b` and `e` above) refer back to the view in order to apply the transformation each time they are dereferenced. Since the view no longer exists, you are experiencing problems.

The best (IMO) solution here would be to author your own view that aggregates a sorted view of objects (`regions()`), a lower bound (`t`), and upper bound (`T`), and optionally two projections (as above), and returns a view of those elements in the range denoted.

The view's `begin()` member would compute the beginning of the range using `lower_bound` _and cache the result_ so that subsequent calls would be O(1). Ditto for `end()` and `upper_bound`. Copying or moving the view would need to invalidate the cache so that the positions are recomputed the next time `begin()` and `end()` are called. (See `ranges::detail::non_propagating_cache` for inspiration here.)

[meta: Yes, please use StackOverflow's `range-v3` tag for these sorts of questions, and save the range-v3 GitHub issues list for bug reports and feature requests. Thanks!]
