### ISSUE TITLE
Please make BUILD_TESTING cmake variable work and only build them when it is on

### ISSUE THREAD

**Issue by yurivict** [ericniebler/range-v3#781]
If the package only needs to install headers, tests shouldn't be built.

**Comment by gnzlbg** [comment]
The problem is that `make` builds the tests. Currently `make test` does not build the tests, it only runs them (and fails if they are not built). 

See: https://stackoverflow.com/a/30130061/1422197

We need to first exclude the `add_executables` from the all target. 

Then, we need to force ctest to build the tests without actually running them. Because CMake is FUBAR, we can't add the tests as dependencies to the `test` target. So we need to do something else. The SO Answer suggest:

* generating a template file containing:

  > execute_process(COMMAND "@CMAKE_COMMAND@" --build . --target test_name)

  for all tests.

* add this as a `TEST_INCLUDE_FILE`

I think this is insane. We should probably just add an option `RANGE_V3_BUILD_TESTS` that is enabled by default, and add test executables, build them, and run the tests only if this option is enabled.

This way @yurivict could just install range-v3 by configuring as `cmake -DRANGE_V3_BUILD_TESTS=Off`. The alternative is to set this option to be off by default.

**Comment by gnzlbg** [comment]
Maybe a better alternative would be to add a custom `check` target that builds the tests and then runs `ctest`. That is, instead of `make test` one would need to write `make check` to first build and then run the tests.

**Comment by CaseyCarter** [comment]
FWIW, after merging #821 tests will not be built if `BUILD_TESTING` is set explicitly.

**Comment by pfultz2** [comment]
> FWIW, after merging #821 tests will not be built if BUILD_TESTING is set explicitly.

That seems like it won't build the tests with `-DBUILD_TESTING=On`.

**Comment by CaseyCarter** [comment]
@pfultz2 Clearer?

**Comment by ericniebler** [comment]
I'm calling this fixed. @yurivict if you disagree please feel free to reopen.
