### ISSUE TITLE
Is RANGES_MODULES for testing?

### ISSUE THREAD

**Issue by yurivict** [ericniebler/range-v3#782]
The way how the ```RANGES_MODULES``` option works now, it is only for testing.
If this is the intent, please say so in the option description. But then what is the benefit of this option.

If this option is for the projects that use it, why isn't ```include/module.modulemap``` installed?

**Comment by gnzlbg** [comment]
> If this option is for the projects that use it, why isn't include/module.modulemap installed?

This option is for projects that use the library, but whether you can use it depends on whether your compiler supports it. 

It is also not tested in CI anymore, so it should definitely not be installed by default.

---

Different issue, the option description says "Enables the Modules TS" but that's off on Clang at least because there it enables clang modules.

**Comment by yurivict** [comment]
> This option is for projects that use the library

But it isn't installed, so they can't use it.

**Comment by gnzlbg** [comment]
> But it isn't installed, so they can't use it.

As I said: 

> it should definitely not be installed by default.

**Comment by yurivict** [comment]
My function here is to create a FreeBSD port. I noticed this problem, but sorry, I can't engage further.

Currently ```RANGES_MODULES``` only sets build options, and ```include/module.modulemap``` is never actually installed. So I guess this should be fixed in the future.

**Comment by gnzlbg** [comment]
Is there any free service that offers CI for FreeBSD ?

**Comment by yurivict** [comment]
I don't know.
