### ISSUE TITLE
Unhelpful diagnostics

### ISSUE THREAD

**Issue by ericLemanissier** [ericniebler/range-v3#796]
While doing some migration from std algorithm to ranges, I've hit several walls with compilation error giving totally unhelpful diagnostics, for example

- ranges::find requiring inequality comparator https://godbolt.org/g/Npy5px
- ranges::copy requiring default construction of the output iterator https://godbolt.org/g/5vydF4

In both cases digging into the requires clause is very tedious, and it seems I'm not alone with this problem:
#323 #234 #189 Microsoft/Range-V3-VS2015#9 #94 

I can see several ways to improve the situation:

1. make the compiler show useful diagnostic, with CONCEPT_ASSERT_MSG ?
2. make the compiler show useful diagnostics by using actual concepts when the compiler implements the concepts TS.  It helps if you have a modern compiler on your computer, and if you godbolt your errors
3. Mention the known pitfalls in the documentation
3. Mention the known pitfalls in the examples and/or tests

Thanks !

**Comment by ericniebler** [comment]
> make the compiler show useful diagnostic, with CONCEPT_ASSERT_MSG ?

In order to make this work, we would need to add overloads of every constrained function that accepts arguments that fail the constraint and place the `CONCEPT_ASSERT_MSG` there. I actually do this in some places, but it's a dirty hack and comes with costs.

> make the compiler show useful diagnostics by using actual concepts when the compiler implements the concepts TS.

This is something I'm actively working on. See the new-concepts-syntax branch, where I'm slowly massaging the syntax of `requires` clauses into something that can be implemented with real concepts on compilers that support them.

> Mention the known pitfalls in the documentation

👍 It should certainly be done, but that assumes people actually read the documentation. 😉
Regardless, it would be helpful the next time someone files a bug like this to have docs to point him or her to.

> Mention the known pitfalls in the examples and/or tests

That doesn't seem like the right place.

**Comment by ericniebler** [comment]
Closing this since the real fix (use real concepts) is a work in progress.
