### ISSUE TITLE
Correct way of dealing with containers/ranges not compatible with range-v3?

### ISSUE THREAD

**Issue by seertaak** [ericniebler/range-v3#810]
I wanted to use `sg14::ring_span` with range-v3. IIUC range complained that type is not semi-regular. I raised a ticket, and soon found myself out my depth:

https://github.com/WG21-SG14/SG14/issues/127

Could an expert please advise as to what the "correct" (from v3 point-of-view) way to proceed is? Am I correct in assuming that in cases such as `sg14::ring_span`, the correct approach is that default constructor leaves the span in a partially-formed state in which only valid operations are destruction (nop) and assignment?

[Again, my apologies if this is not the correct venue for this question. Didn't seem completely appropriate as SO hence post here.]

**Comment by CaseyCarter** [comment]
I [posted a reply in the thread](https://github.com/WG21-SG14/SG14/issues/127#issuecomment-374624372) detailing the requirements of `View` with some explanation. I haven't read the ring span paper in a year or so, so I don't recall if its intent is to model `View` or not.

> ... the correct approach is that default constructor leaves the span in a partially-formed state in which only valid operations are destruction (nop) and assignment?

Yes, that is effectively the case. We've been waffling a bit on whether or not a value-initialized `View` should always represent an empty range, but came down on the side of not imposing that requirement since it rules out some otherwise-useful models `View`.

**Comment by seertaak** [comment]
Thanks for the explanation, and for your input in referenced issue!
