### ISSUE TITLE
Requirements for `max_element`

### ISSUE THREAD

**Issue by sv1990** [ericniebler/range-v3#838]
I have a problem applying `max_element` on the result of `view::join`. It seems to me that `max_element` has too strong requirements by demanding a `ForwardRange`. I think it should work equally well with `InputIterators`.
Here is a minimal example of the problem:
```
#include <range/v3/all.hpp>

#include <vector>
#include <iostream>

int main() {
  std::vector<std::vector<int>> v{{1, 2}, {3, 4}};
  std::cout << ranges::max_element(v | ranges::view::join) << '\n';
}
```

**Comment by gnzlbg** [comment]
`max_element` cannot work for `InputRanges` because it returns a reference to the largest element of the range but that can't be done for ranges whose elements are generated on the fly (`InputRanges`, e.g., think about where the elements of `view::generate` or an `istream_range` live). 

What you might want instead is a different `join` adaptor with different algorithmic guarantees that does not return an `InputRange`.

**Comment by sv1990** [comment]
Thanks for the explanation. That makes sense. 
But why isn't `join` a `ForwardRange`? It seems to me that it fulfils all requirements. What am I missing?
