### ISSUE TITLE
call to 'advance' is ambiguous

### ISSUE THREAD

**Issue by DarkWingMcQuack** [ericniebler/range-v3#845]
When I use the `accumulate` algorithm in my project I get the following error:
```
In file included from /home/XXX/Projects/kylec/src/analysis/lookup/FunctionLookup.cpp:1:
In file included from /home/XXX/Projects/kylec/include/analysis/convertability/CastConvertability.hpp:3:
In file included from /home/XXX/Projects/kylec/include/analysis/convertability/GenericConvertability.hpp:11:
In file included from /home/XXX/Projects/kylec/external/range_v3/include/range/v3/all.hpp:17:
In file included from /home/XXX/Projects/kylec/external/range_v3/include/range/v3/core.hpp:17:
In file included from /home/XXX/Projects/kylec/external/range_v3/include/range/v3/begin_end.hpp:27:
/home/XXX/Projects/kylec/external/range_v3/include/range/v3/utility/iterator.hpp:112:21: error: call to 'advance' is ambiguous
                    advance(i, n);
```

candidates are:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/bits/stl_iterator_base_funcs.h:194:5: note: candidate function [with _InputIterator = __gnu_cxx::__normal_iterator<const ~LongLongType~, _Distance = long]
    advance(_InputIterator& __i, _Distance __n)
```

and 

```
/usr/include/boost/iterator/advance.hpp:68:9: note: candidate function [with InputIterator = __gnu_cxx::__normal_iterator<const ~LongLongType~, Distance = long]
        advance(InputIterator& it, Distance n)
```
I dont realy know if I accidentialy populated the namespace, but if not this could be easily fixed

**Comment by DarkWingMcQuack** [comment]
https://github.com/ericniebler/range-v3/pull/846

**Comment by maikel** [comment]
Can you provide more context? I do not understand why it would choose `boost::advance` here. Do you use `using namespace boost` or `using boost::advance` somehwere?

**Comment by DarkWingMcQuack** [comment]
I did a grep through my entire project and I am never using `using namespace boost` or `using boost::advance`.
I am using `using namespace ranges` quite often, could that be a problem?

**Comment by CaseyCarter** [comment]
I suspect the source of the problem is that `LongLongType` is associated with `namespace boost`, and that both `boost::advance` and `std::advance` are therefore viable causing overload resolution to be ambiguous. The proper fix is probably to incorporate the behavior of range-v3's `advance` overload for `counting_iterator` into the `advance` customization point object itself instead of using ADL to find `advance`. We've been using ADL because of that `counting_iterator` overload, and to allow for the possibility that a standard library may provide overloads or specializations of `advance` in namespace `std` that are more efficient for particular standard library iterators.

**Comment by wickedmic** [comment]
A few days ago I encountered the same problem. In my case I was using range-v3 and boost::geometry, which uses boost::advance(..).

Since the only change I had made was to upgrade boost (before boost 1.65 this ambiguity was not showing up), I thought this was an issue with a change in the boost code. So I filed a [bug report](https://github.com/boostorg/iterator/issues/43) for boost iterator. I also made a small [code example](https://godbolt.org/z/rSfeVi), which is showing the compile error. Maybe this helps in some way.

**Comment by ericniebler** [comment]
As evidenced by the fact that the repro has no range-v3 code in it, this is damage in Boost.Iterator, which introduces an ambiguous overload of `advance`. However, I think we can work around the damage by turning `ranges::advance` into a proper customization point object with a poison-pill overload for `advance`, dispatching via ADL _only_ when a more specialized overload is found.
