### ISSUE TITLE
gcc + view::transform + std::prev = UB

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#862]
The following code compiles and hangs under gcc. Clang refuse to compile with bidirectional error.

```c++
#include <iostream>
#include <vector>
#include <range/v3/view/transform.hpp>

struct Data{
    int x,y;
};

int main() {
    std::vector<Data> datas = { Data{0,1}, Data{1,2}, Data{1,3} };

    const auto xs = datas
                    | ranges::view::transform([](const Data& data) -> int{ return data.x; });

    auto j = std::prev(xs.end(), 1);

    std::cout << "Done" << std::endl;
    return 0;
}
```
If it is RandomAccess, it should be bidirectional.
This compiles and work fine:
```c++
std::cout << xs[2];
```
And this too:
```c++
auto j = xs.end() - 1;
```
So... Is this compiler related error, library related error, or I misunderstand/misuse it?

**Comment by CaseyCarter** [comment]
Iterators that meet the range-v3 `BidirectionalIterator` requirements don't necessarily meet the *standard*'s requirements for bidirectional iterators. Use `ranges::prev` instead of `std::prev` and all should be well.

**Comment by tower120** [comment]
So... just to clarify for myself : this means - I can't use std::lower_bound / std::upper_bound? Because they internally use std::advance?

**Comment by CaseyCarter** [comment]
Yes. In general, you can't pass range-v3 iterators to library components that expect standard iterators because Ranges has differing requirements for the various iterator categories than the standard. You have two choices: use `ranges::foo` instead of `std::foo` (preferred), or adapt your range-v3 iterators/ranges with `common_iterator` / `view::bounded` - which can adapt range-v3 iterators into standard iterators, possibly with a "lower" iterator category - and pass those to `std::foo`.
