### ISSUE TITLE
 Why aren't ranges' iterators compatible with std's iterators?

### ISSUE THREAD

**Issue by xmllmx** [ericniebler/range-v3#896]
```
#include <vector>
#include <iostream>
#include <range/v3/all.hpp>

int main()
{
    auto coll = std::vector{ 1, 2, 3 };

    ranges::copy(
        coll,
        ranges::ostream_iterator<int>{  std::cout, ", " }
    ); // ok

    ranges::copy(
        coll, 
        std::ostream_iterator<int>{ std::cout, ", " }
    ); // error 
}
```

The issue is shown in the code above. I use ranges-v3-0.3.7.

To me, the generic algorithm copy shouldn't care the destination iterator type as long as it meets the requirements of an output iterator.

If so, why aren't ranges' iterators compatible with std's iterators?

see also: [https://stackoverflow.com/questions/52435630/why-arent-ranges-iterators-compatible-with-stds-iterators](https://stackoverflow.com/questions/52435630/why-arent-ranges-iterators-compatible-with-stds-iterators)

**Comment by CaseyCarter** [comment]
The Ranges iterator concepts have different requirements than the standard iterator requirements as a reflection of what we've learned about iterators in the 25-ish years since the STL was standardized. For the most part the Ranges requirements are more strict, as in this example: range-v3 output iterators require default-construction to provide the capability to lazily-initialize class members which standard output iterators do not provide. There are very few requirements the other way as well: Standard input iterators require the `->` operator which the Ranges iterator concepts do not because `->` is useless to most generic code.

So yes, we agree that `copy` shouldn't care about the output iterator other than that it meets the output iterator requirements - the problem here is that standard output iterators don't necessarily model the Ranges output iterator concept.

**Comment by xmllmx** [comment]
Thank you very much for your explanation.

**Comment by ericniebler** [comment]
I'll additionally note that in C++20, standard iterators like `std::ostream_iterator` _will_ meet the stricter requirements of the new concepts, so this won't be a problem forever.
