### ISSUE TITLE
The current single_view should be an action not a view

### ISSUE THREAD

**Issue by pfultz2** [ericniebler/range-v3#92]
Currently, the views are lightweight and non-owning, however the `single_view` is an owning view. It seems semantically the current `single_view` should be an action. And then add a non-owning `single_view` that only accept lvalues, something like this:

```cpp
template<class T>
struct single_view
{
    T* value;
    single_view(T& x) : value(&x)
    {}
    
    T* begin() { return this->value; }
    T* end() { return this->value + 1; }
    
    std::add_const_t<T>* begin() const { return this->value; }
    std::add_const_t<T>* end() const { return this->value + 1; }
};

template<class T>
single_view<T> single(T& x)
{
    return single_view<T>(x);
}
```

So then `action::single` would capture by value(how it currently does) and `view::single` would capture by reference.

**Comment by ericniebler** [comment]
> Currently, the views are lightweight and non-owning, however the single_view is an owning view.

I've gotten into trouble with my choice of terminology when describing ranges. "Lightweight" and "non-owning" aren't quite right, and I've since changed how I talk about these things. The real distinction is that copying and assigning ranges should be O(1); that is, their complexity should not depend on the number of elements in the range. That condition is met by an owning `single_view`. It's copy and assignment operation is O(1) since there is only one object that gets copied.

If you want `single_view` to have reference semantics, you can say: `view::single(ranges::ref(x))`. Use `ranges::ref` instead of `std::ref` since `ranges::reference_wrapper` is DefaultConstructible, but `std::reference_wrapper` is not.
