### ISSUE TITLE
MSVC don't like forwarded classes

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#946]
The following code does not compiles with MSVC 15.9.3
```cpp
#include <iostream>
#include <memory>
#include <vector>

#include <range/v3/view/indirect.hpp>


class Data;

struct Test {
    std::vector<Data*> m_list;

    auto list() {
        return m_list | ranges::view::indirect;
    }
};


class Data {};

int main()
{
    std::cout << Test().list().size();
}
```

With C2139 error, saying that undefined Data class can not be used with  "__is_convertible_to".
LLVM toolchain do compiles this code.

**Comment by CaseyCarter** [comment]
Ouch. The implementation of `common_type` evaluates `std::is_convertible<Data, const Data&>` which violates the (defective) precondition of `is_convertible` (http://eel.is/c++draft/meta.rel#2.sentence-13) that the argument types are "complete types, arrays of unknown bound, or _cv_ void types." And this despite that the specification for `is_convertible` in [[meta.rel]/5](http://eel.is/c++draft/meta.rel#5):

> The predicate condition for a template specialization `is_­convertible<From, To>` shall be satisfied if and only if the return expression in the following code would be well-formed, including any implicit conversions to the return type of the function:
>
> ```c++
> To test() {
>   return declval<From>();
> }
> ```

is perfectly well-formed when `To` is `const T&` and `From` is `T` for an incomplete type `T` since `declval<From>()` is an xvalue with type `T`.

I *hate* bug reports that mean I have to fix the C++ Standard, file a compiler bug, *and* make a workaround for range-v3. But thank you ;)
